### ISSUE TITLE
Layout options

### ISSUE THREAD

**Issue by bag-man** [yuki-yano/fzf-preview.vim#1]
What are the layout options? 

I'm used to fzf.vim with `let g:fzf_layout = { 'down': '~20%' }`, but I can't seem to replicate that at all. I can't even get it to be on the bottom rather than the top. 

This is really awesome though, thanks!

**Comment by yuki-yano** [comment]
fzf-preview uses the window option of fzf#run.
fzf.vim uses another option, it is necessary to change the options.
Try specifying `let g:fzf_preview_layout = 'belowright split new'` and `let g:fzf_preview_rate = 0.2`.

**Comment by yuki-yano** [comment]
Look fzf.vim's window option.
> " In Neovim, you can set up fzf window using a Vim command
> let g:fzf_layout = { 'window': 'enew' }
> let g:fzf_layout = { 'window': '-tabnew' }
> let g:fzf_layout = { 'window': '10split enew' }

**Comment by bag-man** [comment]
Fantastic, thank you. Is there also a way to replicate the fzf_action settings? 

```
  let g:fzf_action = {
    \ 'ctrl-t': 'tab split',
    \ 'ctrl-i': 'split',
    \ 'ctrl-s': 'vsplit' }
```

**Comment by yuki-yano** [comment]
Implemented `g:fzf_action`.
With the restriction of `fzf#wrap`, I had to cut off some of the display of`:GitFilesPreview`.

**Comment by bag-man** [comment]
Oh awesome thanks! I have issues when I open fzf the main window gets corrupted, and it seems to always open in a new tab. However I am using vim not nvim so that may be why. 

EDIT: Hmm tried in nvim, same issues.

**Comment by yuki-yano** [comment]
I am using neovim, but it seems to be working normally.
Does it change even if deleting other fzf settings?
