### ISSUE TITLE
Does this work on Windows?

### ISSUE THREAD

**Issue by benstaniford** [yuki-yano/fzf-preview.vim#105]
I've had fzf.vim working for 6 months or so using both gvim and nvim-qt on Windows.  I've just tried fzf-preview and I'm getting errors as soon as the preview window pops up.  FzfPreviewBuffers for example displays:

Error detected while processing function 394[30]..<SNR>46_callback:
line 21:
Vim(let):E684: list index out of range: 0

Any ideas?

I've read the vim help page, and I've run checkhealth in nvim which shows that nvim and python3 is working etc.  I initially tried on an nvim from 4 months ago, but I've now installed the latest dev release 0.50 and I'm having the same issues.

**Comment by yuki-yano** [comment]
I'm sorry.
I don't have a Windows environment so it's hard to support it.

**Comment by BSDxxxx** [comment]
I got the same error in nvim-qt in Win10.

**Comment by BSDxxxx** [comment]
@benstaniford You may want try `voldikss/vim-floaterm`.
