### ISSUE TITLE
Default filelist command with rg includes misc git files

### ISSUE THREAD

**Issue by jemag** [yuki-yano/fzf-preview.vim#106]
The default command for file list (fzf_preview_filelist_command) is determined by this I believe: 
``` javascript
if !exists('g:fzf_preview_filelist_command')
  if executable('rg')
    let g:fzf_preview_filelist_command = 'rg --files --hidden --follow --no-messages -g \!"* *"'
  else
    let g:fzf_preview_filelist_command = 'git ls-files --exclude-standard'
  endif
endif
```

The git ls-files will properly exclude git internal files while the rg one will not. See:
![image](https://user-images.githubusercontent.com/7985687/78192684-98e68b80-7446-11ea-96ba-af22e7814294.png)

Although we can modify the default command, I believe most users will not want to see git internal files.

To avoid this, I am currently using something like: 
```
let g:fzf_preview_filelist_command = 'rg --files --hidden --follow --no-messages --glob "!.git/*"'

```

**Comment by yuki-yano** [comment]
It is not included in ripgrep because it can be set to ignore in the `.ignore` file.
Many users may want to ignore the `.git` directory by default, so I'm going to consider changing it.

`-g \!"* *"` is required in relation to fzf's delimiter

**Comment by yuki-yano** [comment]
I've recently been ignoring the .git directory with the following configuration, but I'm going to add it to my default configuration.

```
$ export RIPGREP_CONFIG_PATH=$HOME/.config/ripgrep/rc
$ cat ~/.config/ripgrep/rc
--glob=!.git/*
--colors=match:fg:magenta
--colors=match:style:nobold
--colors=path:fg:green
--colors=path:style:bold
--colors=line:fg:cyan
--colors=line:style:bold
```

Thank you very much.
bbcc871799c4760f11fe12749841a82bccaee7cb
