### ISSUE TITLE
dev-icon prefix breaks opening files

### ISSUE THREAD

**Issue by mccurdyc** [yuki-yano/fzf-preview.vim#108]
First, let me say, thank you for fzf-preview.vim. I have been enjoying it greatly!

When I enable dev-icons, it breaks opening files because it tries to open a filename prefixed with the dev-icon which doesn't exist.

**Comment by yuki-yano** [comment]
In my environment, it works normally even if dev-icons is enabled.
Can you write down the minimum configuration and environment you want to reproduce?
I think it would be even easier to solve the problem if there was a GIF.

**Comment by SanD94** [comment]
![demo](https://user-images.githubusercontent.com/8544658/79696683-ef492c00-8286-11ea-86af-ee2db549f53a.gif)

Sorry for the unnecessary parts. I hope this helps.

**Comment by mccurdyc** [comment]
```
$ nvim -u minimal
```

```
$ cat minimal
```

```
call plug#begin('~/.vim/plugged')

Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'yuki-ycino/fzf-preview.vim'

" Always load the vim-devicons very last
Plug 'ryanoasis/vim-devicons' " also requires 'pacman -S ttf-font-awesome, nerd-font-source-code-pro'

call plug#end()

" Commands used to get the file list from project
let g:fzf_preview_filelist_command = 'fd --type f --exclude vendor' " Installed fd

" Commands used to get the file list from current directory
let g:fzf_preview_directory_files_command = 'rg --files --hidden --follow --no-messages -g \!"* *"'

" Use vim-devicons
" ***THIS SEEMS TO BREAK OPENING A FILE!***
" Looks nice, though :)
let g:fzf_preview_use_dev_icons = 1
let g:fzf_preview_dev_icon_prefix_length = 2

" Neither of these work
nmap <C-p> :FzfPreviewDirectoryFiles<CR>
nmap <C-f> :FzfPreviewProjectFiles<CR>
```

**Comment by mccurdyc** [comment]
I'm wondering if it is the `ryanoasis/vim-devicons` plugin or the fonts that I have installed.

```
Kernel: Linux 5.5.8-arch1-1
```

**Comment by mccurdyc** [comment]
The icons and preview display fine.

![20 04 20 09:07:53-snippet](https://user-images.githubusercontent.com/5546264/79755082-7da0ca80-82e6-11ea-9e35-d6bd3db8cd67.png)

But when I open the file, the filename looks odd

**Broken, when opened via FZF preview**
![20 04 20 09:08:41-snippet](https://user-images.githubusercontent.com/5546264/79755149-9f01b680-82e6-11ea-930c-69edc485eb37.png)

**Working perfectly when opened via `nvim go.mod`**
![20 04 20 09:09:19-snippet](https://user-images.githubusercontent.com/5546264/79755226-c789b080-82e6-11ea-82b3-3e762cf24976.png)

**Comment by mccurdyc** [comment]
I enjoy this plugin! Thank you for your work!

**Comment by SanD94** [comment]
The problem is about setting g:fzf_preview_dev_icon_prefix_length to 2. The default value for the variable is 5. Since the length of dev icon is 3 bytes, changing it makes [this part](https://github.com/yuki-ycino/fzf-preview.vim/blob/6fca8e0aa23f2acea2ce53502521d9a83adb979b/autoload/fzf_preview/handler.vim#L71) have some buggy behaviors.

**Comment by mccurdyc** [comment]
Confirmed. Manually setting to `5` worked. Thanks! Closing.
