### ISSUE TITLE
FzfPreviewProjectMruFiles does not work in neovim first time

### ISSUE THREAD

**Issue by sushovannits** [yuki-yano/fzf-preview.vim#114]
Hi
This is great work. Really appreciate.
Just wanted to report that when trying `FzfPreviewProjectMruFiles` for first time in neovim it failed with error that said:
```
Undefined variables: g:neomru#file_mru_path
```
Then after I ran the command once in macvim and then in neovim it started working.

**Comment by yuki-yano** [comment]
Thank you very much.
I'll be removing the dependency on neomru soon, so I'm sure this problem will be resolved.
https://github.com/yuki-ycino/fzf-preview.vim/pull/112
