### ISSUE TITLE
Wrong file being opened

### ISSUE THREAD

**Issue by Brendonk13** [yuki-yano/fzf-preview.vim#115]
Hello,
I am using the following commands but they do not always open an existing file, seems to happen when the 

chosen file is far from vim's pwd.
nnoremap <silent> <leader><M-f> :<C-u>FzfPreviewFromResources<space>directory<CR>

" search files in current directory
nnoremap <silent> <M-f> :lcd %:p:h<CR><bar>:<C-u>FzfPreviewFromResources<space>directory<CR>
Changing this from lcd to cd does not work either.

: FzfPreviewDirectoryFiles<CR> also does not work.
nnoremap <silent> <M-r> :Rooter<CR> <bar> :<C-u>FzfPreviewProjectGrep<space>
also takes me to non-existing files

and :FzfPreviewGitFiles<CR> does not find many of my files

Here are some screenshots (in order executed) from me entering vim then opening 1 file successfully, a second file (near vim's pwd) sucessfully, then the third time it makes some random path and opens a non-existant file.

![fst](https://user-images.githubusercontent.com/36203940/79531752-7cdf0e80-8030-11ea-93c6-da9beccdf1ef.png)

![snd](https://user-images.githubusercontent.com/36203940/79531767-88323a00-8030-11ea-9ba9-602a30a3f91c.png)

This was weird also, I couldn't use the fuzzy finder without having at least 2 buffers open.
![third](https://user-images.githubusercontent.com/36203940/79531772-8a949400-8030-11ea-8b3e-1220be06159e.png)

![fourth](https://user-images.githubusercontent.com/36203940/79531807-9da76400-8030-11ea-85f7-f9c0ad8a471d.png)

![fifth](https://user-images.githubusercontent.com/36203940/79531822-a435db80-8030-11ea-9c33-b42fe0b2b711.png)

some consistent themes in the random paths:
 - part of my pwd shows up twice
 - part of the path is from a terminal: ie  
 hexanome14/Cterm://.//24953:/bin/bash/C#/screens.cs
 - a random 'C' is thrown in often as well:   hexanome-14/Assets/In_Game/Chexanome-14/Assets/In_Game/C#/Action.meta/Screens/ScreenManager.cs
 - note here^ that action.meta is a file yet it is used as if it is a directory.

BASH: bash 5.0.16
OS: 5.4.28-1-MANJARO
Terminal: kitty 0.17.2 or neovim terminal
Downloaded this plugin about 5 hours ago using vim-plug so using whichever version was up then.

**Comment by yuki-yano** [comment]
Thank you for your polite report.

I was concerned about the # in the file path.
Maybe fzf-preview.vim doesn't handle # very well.
Doesn't it work in other directories?
