### ISSUE TITLE
[Question/Suggestion] Integration with FZF

### ISSUE THREAD

**Issue by sheoak** [yuki-yano/fzf-preview.vim#117]
I notice that some methods form fzf.vim where not in fzf-preview, like :History:. Is this ok to make both plugins work together? 

If so, I realized that you could very easily benefit from fzf preview good looking floating window in fzf.vim too, just adding this to init.vim:

    let g:fzf_layout = { 'window': 'call fzf_preview#window#create_centered_floating_window()' }

Not sure if it is safe? Maybe it could be an option in fzf-preview?

**Comment by yuki-yano** [comment]
It's probably fine to use them together.
We were thinking of writing the options in the README, but we haven't been able to verify them, so we haven't been able to write them.

It would be helpful if you could cast an Issue if you try and have a problem.

**Comment by sheoak** [comment]
I'm using this option at the moment and it's working fine, if I see any bug I will open an issue. Thanks!
