### ISSUE TITLE
It would be nice to have better control over size and position

### ISSUE THREAD

**Issue by rlisowski** [yuki-yano/fzf-preview.vim#122]
It would be nice to have better control over size and position, this also implies the possibility to disable `reverse` option for fzf.

eg

```vim
" Ref: https://github.com/Blacksuan19/init.nvim
function! fzf_preview#window#create_centered_floating_window() abort
  if exists('g:fzf_preview_floating_window_rate')
    let width  = float2nr(&columns * g:fzf_preview_floating_window_rate)
    let height = float2nr(&lines * g:fzf_preview_floating_window_rate)
    let top    = ((&lines - height) / 2) - 1
    let left   = (&columns - width) / 2
  else
    let width  = float2nr(g:fzf_preview_floating_window_width)
    let height = float2nr(g:fzf_preview_floating_window_height)
    let top    = float2nr(g:fzf_preview_floating_window_top)
    let left   = float2nr(g:fzf_preview_floating_window_left)
  endif
  " ...
```

and then in config file:
```vim
let g:fzf_preview_floating_window_width  = &columns
let g:fzf_preview_floating_window_height = float2nr(&lines * 0.8)
let g:fzf_preview_floating_window_top    = (&lines - float2nr(&lines * 0.8)) - 1
let g:fzf_preview_floating_window_left   = 0
```

![fzf-preview](https://user-images.githubusercontent.com/7737/80647685-2f6e9280-8a6f-11ea-8507-a1ccfa1346b8.jpg)

Do you think it's a good idea @yuki-ycino?

**Comment by yuki-yano** [comment]
I think it's a very good idea.
However, the code for window.vim is based on reddit, so it's not easy to fix it.

Please let me implement it when I can afford it, as I have a busy work schedule and so on.
Thank you.

**Comment by rlisowski** [comment]
Thanks, @yuki-ycino! For now, I can live with my own fork so not a big issue :)

**Comment by yuki-yano** [comment]
Sorry, when I went to version 2 (to make it work in vim) I changed it to use the floating window and popup implementations that fzf implements directly.
I'm thinking of closing this Issue once, is it OK?

**Comment by rlisowski** [comment]
yep, I'm closing this issue
