### ISSUE TITLE
Can FzfPreviewDirectoryGrep be supported

### ISSUE THREAD

**Issue by sushovannits** [yuki-yano/fzf-preview.vim#123]
Great work on this!!
Was wondering can `FzfPreviewDirectoryGrep` be supported?

**Comment by yuki-yano** [comment]
I'm sorry it took me so long to get back to you.
I'll think about adding it, but I'm thinking about refactoring the plugin before I do so, so it may be late.

**Comment by muniter** [comment]
@sushovannits Here's a quick work around I use to grep in the current file directory, might help you out.

```
function! Fzf_grep_on_current_file_directory()
    let l:wd = execute(':pwd')
    let l:path = expand('%:h')
    execute (':cd' . l:path)
    let l:grep = input('FzfPreviewProjectGrep: ')
    execute(':FzfPreviewProjectGrep' . ' ' . l:grep)
    execute (':cd' . l:path)
```

**Comment by yuki-yano** [comment]
There is a workaround, so let me close it once.
If there are many requests, we'll consider it again.
