### ISSUE TITLE
'$(...) is not supported" error showing in preview window under Fish shell

### ISSUE THREAD

**Issue by jchilders** [yuki-yano/fzf-preview.vim#124]
When opening a preview window using nvim under Fish, the following error shows at the top of the preview window:

```
fish: $(...) is not supported. In fish, please use '(file)'. 
[[ "$(file --mime '<<FILE>>')" =~ binary ]] && echo <<FILE>>"
^
```

Where `<<FILE>>` is the currently selected file in the fzf list window.

![Screen Shot 2020-05-05 at 6 49 22 PM](https://user-images.githubusercontent.com/105418/81126566-40048a00-8f01-11ea-8771-e4f70b077c66.png)

Fixing this is simply a matter of setting the following in `~/.config/nvim/config.nvim`:

```
let g:fzf_preview_if_binary_command = "string match 'binary' (file --mime {})"
```

I attempted to find a place in the plugin itself to add this, but do not see a hook for where to do so. Are there any suggestions about how best -- or even if -- to integrate this change?

**Comment by yuki-yano** [comment]
I couldn't reproduce this problem using fish, but I was able to confirm it by setting the default shell to fish.

Changing fish to the default shell can cause problems, so change it to run fish from a POSIX-compatible shell.
For example, by writing `exec fish` in .bashrc or .bash_profile, you can invoke fish with bash as the default shell.

**Comment by yuki-yano** [comment]
Try https://github.com/yuki-ycino/fzf-preview.vim/issues/96#issuecomment-607591685

**Comment by cjbarroso** [comment]
Fix worked for me on ubuntu20 with fish shell and neovim
