### ISSUE TITLE
FZFPreviewDirectoryFiles only shows files without space in their names

### ISSUE THREAD

**Issue by ibnishak** [yuki-yano/fzf-preview.vim#125]
This is [possibly an error in fzf too](https://github.com/junegunn/fzf.vim/issues/554). 

OS: Linux
VIm: Neovim

**Comment by yuki-yano** [comment]
I'm hiding it because it's prone to causing bugs in my environment.
I'm sorry, but please respond by changing the space to an underbar.

**Comment by ibnishak** [comment]
ok
