### ISSUE TITLE
FzfPreviewLines is broken with the default rg --line-number --no-heading command

### ISSUE THREAD

**Issue by pawelduda** [yuki-yano/fzf-preview.vim#127]
Commit: `765b9b3b29fd625aa76f5a517f83309269fdfea0`

When trying to use `:FzfPreviewLines`, in preview window I get:
```
Cannot process the entry :(
Please open an issue and describe what happened
including information such as file name and g:fzf_preview_grep_cmd
```

And when I press enter, this happens:
```
Error detected while processing function 316[30]..<SNR>71_callback:
line   21:
Vim(call):E684: list index out of range: 2
Press ENTER or type command to continue
```

My `g:fzf_preview_grep_cmd` was the default one: `rg --line-number --no-heading`

I managed to make it work by setting:
`let g:fzf_preview_lines_command = "awk '{if (NF>0) print NR, $0}'`

**Comment by yuki-yano** [comment]
Thanks for the report.
Does that happen on every line?

**Comment by pawelduda** [comment]
As far as I checked, it did happen on every line. Since using my `awk` workaround, I haven't run into this problem yet.

**Comment by yuki-yano** [comment]
Thank you very much.
I looked it up in my environment and couldn't reproduce the problem.
I will write to Issue when I find out what caused it.
