### ISSUE TITLE
:FzfPreviewDirectoryFiles too slow with devicons

### ISSUE THREAD

**Issue by sheoak** [yuki-yano/fzf-preview.vim#128]
If dev icons are enabled, then using :FzfPreviewDirectoryFiles on a large number of files will be very slow and vim hangs. See commented code below.

```
function! s:create_dev_icon_list(files) abort
  let result = []

  " this loop, even empty, is too slow, because the array is huge
  for file in copy(a:files)
    let file = split(file, ':')[0]
    let filename = fnamemodify(file, ':p:t')
    let icon = WebDevIconsGetFileTypeSymbol(substitute(filename, '\[[0-9;]*m', '', 'g'), isdirectory(filename))
    call add(result, s:dev_icon_format(icon))
  endfor

  return result
endfunction
```

**Comment by sheoak** [comment]
Is it possible to add devicons only on fzf output on the screen? This would greatly improve the plugin performances

**Comment by yuki-yano** [comment]
FZF basically gets all the listings first, so it's going to be hard to deal with.

It may be possible, but the code would need to be significantly modified to change the way FZF is used.

**Comment by sheoak** [comment]
I create a temporary workaround that disable devicons if the number of files is too high, if you are interested. I'm sending a PR, feel free to reject if it's not to your taste :)

**Comment by yuki-yano** [comment]
TypeScript's implementation of devicons makes it 200-300 times faster than Vim script.
It seems to be fast enough without this setting.

**Comment by yuki-yano** [comment]
I added this Issue configuration and then migrated to the remote plugin.
#133
