### ISSUE TITLE
Unexpected error when using any command

### ISSUE THREAD

**Issue by svanharmelen** [yuki-yano/fzf-preview.vim#13]
I get this error for each `FzfPreview` commands that I'm trying to use. Just pressing `enter` hides the message and opens the preview window. Anything I can o to solve that?

<img width="402" alt="image" src="https://user-images.githubusercontent.com/4171547/73975334-662c8500-4926-11ea-93b5-d8f5ce34abf2.png">

**Comment by yuki-yano** [comment]
This error occurred in my environment, but it seems that vim-bufkill and this plugin are not compatible.
I moved to [vim-sayonara](https://github.com/mhinz/vim-sayonara) and the problem was solved.

**Comment by svanharmelen** [comment]
Thanks for the feedback! But that's a shame as I use a few `vim-bufkill` features that are not offered by `vim-sayonara`. Maybe I can find some time to see if I can understand why this error occurs, but that will not be any time soon 😞

**Comment by yuki-yano** [comment]
I don't think it's a problem with this plugin, so let me close
