### ISSUE TITLE
[Question] Open all files from :FzfPreviewGitFiles

### ISSUE THREAD

**Issue by FL3SH** [yuki-yano/fzf-preview.vim#136]
It is possible to open all files from current `:FzfPreviewGitFiles`view as new tabs?

**Comment by yuki-yano** [comment]
You can press Ctrl-t to open it in a different tab.
If you have selected more than one item, each item will open in a different tab.

**Comment by FL3SH** [comment]
Awesome, that's all I needed.
Was it somewhere in docs?

**Comment by yuki-yano** [comment]
It's written in the `Fzf window Keymaps` in the README.

```
<C-x>
  Open split

<C-v>
  Open vsplit

<C-t>
  Open tabedit
```
