### ISSUE TITLE
Commands broken after upgrading to v2

### ISSUE THREAD

**Issue by deevus** [yuki-yano/fzf-preview.vim#139]
Upgraded to version 2 now none of the commands work:

```
Error detected while processing function remote#define#CommandBootstrap[5]..remote#define#request:                                                                                           
line    2:                                                                                                                                                                                   
Error invoking '/home/deevus/dotfiles/.config/nvim/plugged/fzf-preview.vim:command:FzfPreviewBuffers' on channel 4:                                                                          
Error: nvim_call_function: Vim(execute):E731: using Dictionary as a String
```

**Comment by yuki-yano** [comment]
In my environment, I've seen it work with the following minimum configuration.
Does the same error occur with other commands?

```
call plug#begin('~/.vim/plugged')

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'yuki-ycino/fzf-preview.vim', { 'do': ':FzfPreviewInstall' }

call plug#end()
```

**Comment by yuki-yano** [comment]
And, if you can, may I ask you to rm the plugged folder once and try to install it again?

**Comment by deevus** [comment]
> And, if you can, may I ask you to rm the plugged folder once and try to install it again?

I tried this and had the same error message.

**Comment by deevus** [comment]
I should note that I'm using neovim master. Just installed from HEAD https://github.com/neovim/neovim/tree/b39edb5b605b545843482c70a3a3d03e2331a059

**Comment by deevus** [comment]
I just tried 0.4.3 and had the same issue, so it's not some new issue with 0.5.0.

**Comment by deevus** [comment]
Ok I don't know what I did, but I nuked the `plugged` directory and reinstalled `neovim` and now it's working :man_shrugging:

**Comment by wbthomason** [comment]
I am still seeing this behavior intermittently with Neovim from master. Additionally, as I mentioned in #138, `UpdateRemotePlugins` sometimes generates an empty signature for this plugin, which seems related...

**Comment by yuki-yano** [comment]
Sorry, I haven't been able to reproduce it in my environment.
Is there a reproducible procedure?
Does running UpdateRemotePlugins several times cause the command to be removed?

**Comment by wbthomason** [comment]
I unfortunately can't give you instructions for 100% consistently reproducing it - the closest I've come is noting that `UpdateRemotePlugins` works when run inside the `fzf-preview.vim` directory, but _usually_ does not work when run in some other directory.

**Comment by yuki-yano** [comment]
If the plugin fails to load outside of the git project and there was a bug that prevented `UpdateRemotePlugins` from working properly.
I've fixed it in the following commit so you can try it out.
https://github.com/yuki-ycino/fzf-preview.vim/commit/9682011c2f0fb3afc2343e913a041ba55b7f11a5

**Comment by wbthomason** [comment]
This seems to be working much better, thank you!
