### ISSUE TITLE
FzfPreviewProjectGrep fails with lots of files

### ISSUE THREAD

**Issue by lynndylanhurley** [yuki-yano/fzf-preview.vim#140]
I just started getting this error after upgrading to v2 this morning:

```
Error detected while processing function remote#define#CommandBootstrap[5]..remote#define#request:
line    2:
Error invoking '/Users/lynn/.vim/bundle/fzf-preview.vim:command:FzfPreviewProjectGrep' on channel 6:
Error: Failed grep command: "rg --line-number --no-heading --color=always ."
```

Here is my config:

```
Plug 'yuki-ycino/fzf-preview.vim', { 'do': ':FzfPreviewInstall' }

" ...

nnoremap <Leader>/ :FzfPreviewProjectGrep .<CR>
```

This does work as expected with smaller directories.

I have tried removing the plugin folder and re-installing.

**Comment by yuki-yano** [comment]
I am currently setting the maximum buffer size I can receive from the command to 100MB.
It is probably over that and is causing an error.

I've changed the maximum to 1000MB so please try again.
https://github.com/yuki-ycino/fzf-preview.vim/commit/91c690d1d76f5ca647b3213210bbe8f78c2c1860

However, I feel that going over 100MB is not good for performance.
I will consider changing the default value to 100MB to make it changeable.

**Comment by lynndylanhurley** [comment]
@yuki-ycino that worked! Is there any way to tell `rg` to truncate the results? I'll probably only ever need the first 100 items or so.

**Comment by yuki-yano** [comment]
Is grep with `FzfPreviewProjectGrep {word} {dir}` insufficient to grep?

**Comment by lynndylanhurley** [comment]
@yuki-ycino my ideal usage would be:

1. I open the search popup with a key mapping (mine is currently mapped to `<Leader>/`).
2. As I start typing, the search results are narrowed down to the best matches. This is helpful because I usually don't know the exact string I'm searching for, and it's nice to get feedback as I type.

The issue with `FzfPreviewProjectGrep {word} {dir}` is that it I don't get the feedback as I type the `{word}` part.

Is there a better way to accomplish what I'm trying to do?

**Comment by yuki-yano** [comment]
Try FzfPreviewProjectCommandGrep.

**Comment by yuki-yano** [comment]
Support dynamic options and show arguments in grep
https://github.com/yuki-ycino/fzf-preview.vim/commit/c115de57e681f3c095309580b9805bf819fb2395

![スクリーンショット 2020-07-16 19 36 40](https://user-images.githubusercontent.com/5423775/87667555-86018800-c7a5-11ea-84a9-1d7a578c7600.png)
