### ISSUE TITLE
fzf-preview.vim symlink: bad effect in windows and msys symlink enabled

### ISSUE THREAD

**Issue by tsuyoshicho** [yuki-yano/fzf-preview.vim#142]
## Problem

`fzf-preview.vim/rplugin/node/fzf-preview.vim` symlink to top of repo.

When dein recache runtime are ran, but this symlimk loop in windows

see below (dein generate command in temp batch file)

```batch
robocopy.exe "C:\Users\username\.cache\dein\repos\github.com\yuki-ycino\fzf-preview.vim" "C:\Users\username\.cache\dein\.cache\.vimrc\.dein" /E /NJH /NJS /NDL /NC /NS /MT /XO /XD ".git"
```

## Configuration

1. symlink enabe.
2. symlink enable git for windows clone to this repo.
3. run above command.

\# This issue is report only.

**Comment by yuki-yano** [comment]
Thanks.
Fixed from 404f5a7897cdb46ce7398d8aa3087818fe5b78bf
