### ISSUE TITLE
Plugin broken if CoC is not installed

### ISSUE THREAD

**Issue by wbthomason** [yuki-yano/fzf-preview.vim#144]
Since one of the recent commits, I get an error "Unknown function: CocAction" after selecting any item with this plugin. This makes sense - I do not have `coc.nvim` installed - but does break the functionality of the plugin.

**Comment by reisnobre** [comment]
If you check the migration to v2 page, I think coc.nvim is required.

**Comment by wbthomason** [comment]
@reisnobre Thanks, but I don't think that's the case - the migration guide says "You can use Remote Plugin or coc extensions.", which implies to me that the remote plugin interface (which I'm using) should be fine in the absence of `coc.nvim`.

**Comment by reisnobre** [comment]
Gotcha, maybe you are right. I'm having some trouble with the application, maybe its because I'm trying to use both at the same time.

**Comment by yuki-yano** [comment]
I had set it to use coc from Remote Plugin by mistake.
Fixed: https://github.com/yuki-ycino/fzf-preview.vim/commit/4762b8a382fb400e0e298c6d7a14202772a81cb4

**Comment by wbthomason** [comment]
I no longer see this error, thanks!
