### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by tsara27** [yuki-yano/fzf-preview.vim#145]
Hello,

I've upgraded this plugin to current version and have coc-fzf-preview installed. I can open the popup and search the file. But, when I hit enter, it seems cannot open the file. Attach this screenshot for the example.

![Peek 2020-07-13 22-41](https://user-images.githubusercontent.com/3486644/87324459-4f83fd00-c55a-11ea-8ab0-277b673f9f2d.gif)

Thank you

**Comment by tsara27** [comment]
Just found this error message.

```
Command: fzf-preview.FzfPreviewOpenFileEnter not found
```

**Comment by yuki-yano** [comment]
Are you passing coc as the second argument to the `fzf_preview#remote#process#get_default_processes` ?

> " Get the initial value of the open file processes
> " processes_name is 'open-file', 'open-bufnr', 'register' and 'open-pr'.
> " plugin_type is 'remote' or 'coc'. Default value is 'remote'
> call fzf_preview#remote#process#get_default_processes({processes_name}, {plugin_type})

**Comment by yuki-yano** [comment]
Sorry, the problem seems to occur even if you don't use the function.
I'll fix it.

**Comment by yuki-yano** [comment]
Fixed: https://github.com/yuki-ycino/fzf-preview.vim/commit/1cf06ecc06d1ea93e527286d66240c87bb1c2291

**Comment by tsara27** [comment]
Thanks!
I very appreciate for the quick fix for this issue. :tada:
