### ISSUE TITLE
Loading buffers is extremely slow

### ISSUE THREAD

**Issue by wbthomason** [yuki-yano/fzf-preview.vim#146]
Using this plugin, I see a startup time of ~200ms going to "opening buffers". Without this plugin, this stage of startup takes ~0.8ms.

Could you point me to the code that's running on the various buffer opening events?

**Comment by yuki-yano** [comment]
Sorry, I recently put in an implementation of caching the contents of MRU and MRW.
https://github.com/yuki-ycino/fzf-preview.vim/blob/89b323cb163a6ad8af896578e2d6fc9ef8abbed6/src/fzf/cache/index.ts#L9-L26

It wasn't a problem in my environment, but it may be causing the slowdown in some environments.
I'm going to add a setting to the plugin so that I can use the cache or configure it.

**Comment by yuki-yano** [comment]
Disabled MRU and MRW look-ahead caching by default.
https://github.com/yuki-ycino/fzf-preview.vim/commit/9ba8a9c1d6867590bf37f47f51d0b7c2724ed5ba

However, it looks like it's still taking a while to call autocmd via RPC.
I'm going to add a setting to disable MRU and MRW in the future, and move autocmd to Vim script.

**Comment by yuki-yano** [comment]
Moved autocmd implementation to Vim script
https://github.com/yuki-ycino/fzf-preview.vim/commit/5db5559fa151e3481aba75e75ddaa793f7563b51

Try this to see if it improves things.

**Comment by wbthomason** [comment]
Unfortunately, this mostly seems to have just shifted the load time cost to the `VimEnter` event...

**Comment by yuki-yano** [comment]
Changed VimEnter processing from Vim script to use a timer to do asynchronous processing.
Fixed: https://github.com/yuki-ycino/fzf-preview.vim/commit/d811675b6059c03b2e7b5aa407cb2e9c2c633695

Here are the results as measured in my environment.
However, executing commands in the middle of the initialization process may cause problems.

```
event                  time percent

// Not Install
BufEnter autocommand  61.94   15.07
VimEnter autocommand  18.39    4.48

// Before improvement
BufEnter autocommand  62.63    9.10
VimEnter autocommand 226.22   32.87

// After improvement
event                  time percent
BufEnter autocommand  61.83   15.31
VimEnter autocommand  19.19    4.75
```

**Comment by reisnobre** [comment]
Just for a sanity check, how are you guys profiling those events?

**Comment by wbthomason** [comment]
@reisnobre I use https://github.com/dstein64/vim-startuptime, averaged over 10 trials.

**Comment by yuki-yano** [comment]
I'm the same way.

@wbthomason Has the problem been resolved?

**Comment by gavsim** [comment]
To add, I'm seeing similar behaviour with the latest version 0.2.0 - loading buffers is really slow.

**Comment by reisnobre** [comment]
There's a bit of a delay when opening a buffer

BufEnter autocommand  13.45    5.20
VimEnter autocommand   0.09    0.03

**Comment by yuki-yano** [comment]
Is the buffer opening slowly when using the fzf-preview command?
Are all BufEnter events taking a long time?

**Comment by yuki-yano** [comment]
And which plugin do you use, Remote Plugin mode or coc extensions mode?

**Comment by reisnobre** [comment]
I'm using it via `coc-extension`.
I tested with `coc-explorer` extension and the opening of buffers is instantaneous.

**Comment by yuki-yano** [comment]
Hmmm, fzf-preview calls the Node function twice in RPC when opening the file.
It seems likely that the time it takes to run RPC is an overhead.

It might be faster if the file-opening process is implemented in Vim script, but TypeScript is more desirable from a design standpoint.

**Comment by wbthomason** [comment]
I'm no longer seeing the ~200ms delay (using the remote plugin).

**Comment by yuki-yano** [comment]
The slow VimEnter and BufEnter issue seems to have been resolved, so I'll close this Issue.
If the other parts are slow, create a separate Issue.

Also, a setting that can disable autocmd used by MRU and MRW was added.
https://github.com/yuki-ycino/fzf-preview.vim/commit/deddea9af8328dc8b10d2046c35c00f024cd3859

Please try it out if you need it.
