### ISSUE TITLE
[coc.nvim] Command: fzf-preview.HandleResource not found

### ISSUE THREAD

**Issue by reisnobre** [yuki-yano/fzf-preview.vim#147]
The coc integration seems to work but when I attempt to open a file it throws this error

For the command `:CocCommand fzf-preview.ProjectFiles` it gives me [coc.nvim] Command: fzf-preview.HandleResource not found. 
Also, trying to call the HandleResource manually doesn't seem to work.

**Comment by reisnobre** [comment]
Using the following minimal configuration I the file just doest open without any error or warning.

```
""""""""""""""""""""""""""""""                                                
" => Plugins                                                                 
""""""""""""""""""""""""""""""          
                                                                                                                                                                                                      
call plug#begin()                                                                                                                                                                                     
Plug 'https://github.com/neoclide/coc.nvim', {'branch': 'release'} " lsp and more                                                                                                                     
Plug 'https://github.com/junegunn/fzf', { 'do': './install --bin' } " fuzzy finder                                                                                                                    
Plug 'https://github.com/ryanoasis/vim-devicons' " nice devicons on vim
Plug 'https://github.com/yuki-ycino/fzf-preview.vim'
               
call plug#end()  
               
" =============== FZF Preview
nnoremap <silent> <C-p> :CocCommand fzf-preview.ProjectFiles<CR>
```

**Comment by yuki-yano** [comment]
Try not to install the vim plug if you are using coc extensions.
#145 may have solved the problem, but do you still get the error?

**Comment by reisnobre** [comment]
```
""""""""""""""""""""""""""""""                                                
" => Plugins                                                                 
""""""""""""""""""""""""""""""          
                                                                                                                                                                                                      
call plug#begin()                                                                                                                                                                                     
Plug 'https://github.com/neoclide/coc.nvim', {'branch': 'release'} " lsp and more                                                                                                                     
Plug 'https://github.com/junegunn/fzf', { 'do': './install --bin' } " fuzzy finder                                                                                                                    
Plug 'https://github.com/ryanoasis/vim-devicons' " nice devicons on vim
  
call plug#end()
                 
" =============== FZF Preview
" Use vim-devicons
" let g:fzf_preview_use_dev_icons = 1
                 
" devicons character width
" let g:fzf_preview_dev_icon_prefix_length = 2
nnoremap <silent> <C-p> :CocCommand fzf-preview.ProjectFiles<CR>
```

I've changed to only use the `coc` version and the same occurs, but without any errors, as mentioned above.
The floating window opens, the files are listed but selecting one just fails without any errors or warnings.

![Screen Shot 2020-07-14 at 09 27 17](https://user-images.githubusercontent.com/12832066/87425566-3f990700-c5b4-11ea-8758-b5cb5381edfc.png)

I hope this image is helpful.

**Comment by yuki-yano** [comment]
Hmmm, as the GIF shows, it works fine in my environment.
Do I get the same error if I delete the directory where the plugin is installed and start over?

![Kapture 2020-07-14 at 21 43 21](https://user-images.githubusercontent.com/5423775/87427197-6179a480-c61b-11ea-8b21-294452afb618.gif)

**Comment by yuki-yano** [comment]
It doesn't seem to work with some versions of Node.
I can confirm that it doesn't work on v10 but works on v14 in my hand.
Can you raise the version of Node?

**Comment by reisnobre** [comment]
Ok, I upgraded my node version to 14.5 and now it's working.

Can you add this requirement on the upgrade page to the readme document?

**Comment by yuki-yano** [comment]
OK. 
However, it's difficult to identify where the problem is occurring, so I'll likely just list the versions I've been able to verify in my environment.

**Comment by reisnobre** [comment]
Thanks

**Comment by reisnobre** [comment]
I would love to help on the project, is there a discord or maybe another type of communication where I can learn more about how the project was written?

**Comment by yuki-yano** [comment]
By changing the build target to es2017, I was able to confirm that it works with Node10.
Fixed: https://github.com/yuki-ycino/fzf-preview.vim/commit/b36d0f467ca8c6dfdb3ae41f33c22e1fce8ab737

Can I use this Issue because my English is not very good and it's going to be difficult for me to speak in chat? (I don't use Discord much.)

**Comment by reisnobre** [comment]
Sure, if you don't mind. English isn't my first language either. The help that I was looking for was via chat anyway.
