### ISSUE TITLE
Fail at first time running `FzfPreviewProjectGrep "a"` ( double quoted string )

### ISSUE THREAD

**Issue by LumaKernel** [yuki-yano/fzf-preview.vim#148]
## Environment

Neovim: NVIM v0.5.0-418-g87d892afa
OS: Ubuntu Bionic
Installed as Neovim RemotePlugin with dein.vim.
Using latest version of fzf-preview.vim.

## Repro.

1. Right after booting neovim,
2. `FzfPreviewProjectGrep "a"`
3. Got `E116: Invalid arguments for function remote#define#CommandBootstrap`
4.  `FzfPreviewProjectGrep a` - it works
5. After step 4, `FzfPreviewProjectGrep "a"` works.

Please let me know if it is not reproduced. Thank you.

**Comment by LumaKernel** [comment]
Ah. It seems not good usage. ( double quoting )

**Comment by yuki-yano** [comment]
It may be relevant to this issue.
https://github.com/neovim/neovim/issues/12410

The fixes have been merged, does this still happen in the latest version?

**Comment by LumaKernel** [comment]
It works fine. Thank you!
