### ISSUE TITLE
Migration to v2: search result list is upsidedown

### ISSUE THREAD

**Issue by tuxflo** [yuki-yano/fzf-preview.vim#149]
Hi!
I just did the migration to v2 and changed my bindings to the new ones. Everythings is working good so far. However after using it for a while I realized, that in version 2 the list is on top, and the input is on the bottom. This breaks my habit of using <C-n> to go through the result list.
Is there an option to turn it the other way round again (like in the screenshots inside the Readme.md of this repo) in version 2?
Thanks in advance,
tuxflo

**Comment by yuki-yano** [comment]
I didn't mean to change it, but I think passing the `--reverse` option would work.
Try adding `--reverse` to `$FZF_DEFAULT_OPTS` or add `--add-fzf-arg=--reverse` when you run the command.

**Comment by tuxflo** [comment]
Yes adding `--reverse` to the DEFAULT_OPTS worked like a charm, thanks a lot for the quick response :ok_hand:

**Comment by yuki-yano** [comment]
@tuxflo 
You can now use `g:fzf_preview_default_fzf_options` to pass default options.
The default value is `{ '--reverse': v:true }` .
https://github.com/yuki-ycino/fzf-preview.vim/commit/85732ce512db3917505a6784019cc586fd9d5ec8
