### ISSUE TITLE
[coc.nvim]: error when not in a git repository

### ISSUE THREAD

**Issue by TheEdoRan** [yuki-yano/fzf-preview.vim#150]
I get this error when I open a buffer that is not in a git repository, without the plugin no errors show up.

![immagine](https://user-images.githubusercontent.com/1337629/87747854-ad337600-c7f4-11ea-80e1-142faf0344f0.png)

**Comment by yuki-yano** [comment]
I've fixed it and released coc-fzf-preview, so please try it out.
Fixed: https://github.com/yuki-ycino/fzf-preview.vim/commit/5b0f5c6359accf51cb8bea7b418b070d06f57e88

**Comment by TheEdoRan** [comment]
Just tried it, now it's working as expected. Thank you for your awesome work and for the super quick fix!
