### ISSUE TITLE
Is it possible to make the "Project" commands follow pwd?

### ISSUE THREAD

**Issue by brandoncc** [yuki-yano/fzf-preview.vim#155]
I use coc-project to switch between projects, but the project commands only care what directory I start nvim. Is it possible to make them respect the current working directory?

**Comment by yuki-yano** [comment]
Fixed a bug where the path could not be obtained when executing a command from TypeScript.
8ae82aa644baab6849ac1dadda4fac8e6542c797
1362481b49a5ef73235e6de8ddbe64ec9077d9d7

Make sure it's OK.

**Comment by yuki-yano** [comment]
The bug was still there, so I fixed it.
https://github.com/yuki-ycino/fzf-preview.vim/commit/1a63eeab492b7aaf37ec28eabf34c4aa1f6c169d
