### ISSUE TITLE
opening files from `ProjectGrep` no longer working

### ISSUE THREAD

**Issue by burgessa23** [yuki-yano/fzf-preview.vim#159]
Hi,

after updating to latest version, selecting a file in the results for projectGrep opens an empty buffer with extra chars in the title.

using:
```
nnoremap          [fzf-p]gr    :<C-u>CocCommand fzf-preview.ProjectGrep<Space>
xnoremap          [fzf-p]gr    "sy:CocCommand   fzf-preview.ProjectGrep<Space>-F<Space>"<C-r>=substitute(substitute(@s, '\n', '', 'g'), '/', '\\/', 'g')<CR>"
```

to trigger command

in this example, I attempted to open `middleware.js`
<img width="659" alt="Screen Shot 2020-07-26 at 15 03 26" src="https://user-images.githubusercontent.com/292498/88490540-2f3c4100-cf51-11ea-93e2-8003080a3b61.png">

**Comment by yuki-yano** [comment]
It works in my environment, but it may be that different languages handle escape sequences differently.

I changed the default grep command to not colorize.
Try again without setting `g:fzf_preview_grep_cmd`.

https://github.com/yuki-ycino/fzf-preview.vim/commit/c1e1ba2b7a233e1983b57ffe3c47dfe824b97af3

**Comment by brandoncc** [comment]
I just came to open the same issue, my files look like:

```
^[[0m^[[35mapp/javascript/components/project_organization/Organizer.jsx^[[0m
```

I do not have any setting for `g:fzf_preview_grep_cmd`.

**Comment by yuki-yano** [comment]
Thanks, I'll look into it some more.
Do you get the same problem with 0.3.3?

**Comment by burgessa23** [comment]
I'm on `NVIM v0.5.0-0c43655`

**Comment by yuki-yano** [comment]
Sorry for the confusion.
I just updated the plugin so please make sure it's the latest version.
If the version written in the package.json of the plugin is 0.3.3, it's the latest.

**Comment by brandoncc** [comment]
I just updated, and it is fixed. Thank you!

**Comment by burgessa23** [comment]
same here 0.3.3 fixes this issue, thanks for the quick response!
