### ISSUE TITLE
Jumps is broken

### ISSUE THREAD

**Issue by brandoncc** [yuki-yano/fzf-preview.vim#160]
Since I updated a few days ago, I see this:

<img width="1115" alt="Screen Shot 2020-07-27 at 3 31 44 PM" src="https://user-images.githubusercontent.com/543973/88598596-7e03dc80-d01e-11ea-9631-ecbc72447603.png">

`echo g:fzf_preview_grep_cmd` prints:

```
rg --line-number --no-heading --color=never
```

**Comment by yuki-yano** [comment]
I don't know why, as it works in my environment with minimal settings.
Can you try the minimum configuration?

```
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'ryanoasis/vim-devicons'
call plug#end()

let g:coc_global_extensions = ['coc-fzf-preview']
```

![スクリーンショット 2020-07-28 14 02 57](https://user-images.githubusercontent.com/5423775/88621431-6c343f00-d0db-11ea-892c-1fb291021542.png)

**Comment by brandoncc** [comment]
I put that in a file called test.vim, and executed `nvim -u test.vim`. When I run `:FzfPreviewJumps`, I see:

```
Error detected while processing function remote#define#request:
line    2:
Error invoking '/Users/brandoncc/.config/nvim/plugged/fzf-preview.vim/rplugin/node/fzf-preview.vim:command:FzfPreviewJumps' on channel 5:
Error: nvim_call_function: Vim:E117: Unknown function: fzf_preview#remote#resource#jumps#get
```

**Comment by yuki-yano** [comment]
Sorry, the above was a minimal configuration of coc extensions.
Try running `:CocCommand fzf-preview.Jumps` .

**Comment by brandoncc** [comment]
Scratch that last comment, I figured out I needed to run `:PlugInstall` with your config. This is what I get:

![image](https://user-images.githubusercontent.com/543973/88623157-36e70d00-d059-11ea-9ed3-ec7ddeca321a.png)

Here is my list of jumps when I run `:jumps`:

![image](https://user-images.githubusercontent.com/543973/88623229-5d0cad00-d059-11ea-8796-d55cc79fa678.png)

**Comment by brandoncc** [comment]
I also just tried `:clearjumps` and moving around, it starts a new broken list.

**Comment by yuki-yano** [comment]
Hmmm, it's hard to fix because it doesn't reproduce.
Are the other commands working fine?

**Comment by yuki-yano** [comment]
I created a minimum configuration Docker image and tried it on Linux, but I couldn't reproduce it.
Is it possible to create a dockerfile that reproduces the image?

![スクリーンショット 2020-07-28 19 30 34](https://user-images.githubusercontent.com/5423775/88654823-dca58500-d108-11ea-9371-e903269d4096.png)

```
FROM ubuntu:bionic

# Neovim
RUN apt-get update && apt install -y ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip git

WORKDIR /usr/local/src
RUN git clone https://github.com/neovim/neovim.git

WORKDIR /usr/local/src/neovim
RUN make && make install

# Node
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt install -y nodejs

# bat
RUN curl -sL https://github.com/sharkdp/bat/releases/download/v0.15.4/bat_0.15.4_amd64.deb -o bat_0.15.4_amd64.deb
RUN dpkg -i bat_0.15.4_amd64.deb

# vim plugin
RUN sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
RUN mkdir -p /root/.config/nvim
RUN echo " call plug#begin('~/.vim/plugged') \n\
Plug 'junegunn/fzf', {'dir': '~/.fzf', 'do': './install --all'} \n\
Plug 'neoclide/coc.nvim', {'branch': 'release'} \n\
call plug#end() \n\
\n\
let g:coc_global_extensions = ['coc-fzf-preview'] \n" >> /root/.config/nvim/init.vim

RUN nvim +PlugInstall +qa!

ENTRYPOINT ["nvim"]
```

**Comment by brandoncc** [comment]
Sorry I didn't get back to you, I have been really busy. Don't worry about it, I just won't use that command. Thanks anyway!
