### ISSUE TITLE
Weird colors

### ISSUE THREAD

**Issue by felippepuhle** [yuki-yano/fzf-preview.vim#162]
Hey guys, how is it going?

First of thanks for the amazing job, I'm really loving using `fzf-preview`.

I'm getting some weird colors here on my terminal:

![Screen Shot 2020-07-28 at 10 29 04 PM](https://user-images.githubusercontent.com/15961929/88746030-dd96e080-d121-11ea-95a6-0951f0ca15e6.png)

On the left side I ran `bat ./src/AppScreens.tsx --theme=Nord` on the terminal and the colors are correct.
On the right side is `fzf-preview` with `let $FZF_PREVIEW_PREVIEW_BAT_THEME='Nord'`

Thoughts?

Thanks!

**Comment by phongvcao** [comment]
You need to set the `g:fzf_preview_fzf_color_option` variable according to `fzf-preview.vim` doc [here](https://github.com/yuki-ycino/fzf-preview.vim/blob/master/doc/fzf_preview_vim.txt).

Here are some values/ideas from `junegunne/fzf`: https://github.com/junegunn/fzf/wiki/Color-schemes

I use solarized dark and here is what I have in my `.vimrc`:
```vim
" fzf-preview.vim settings
let g:fzf_preview_fzf_color_option = 'dark,hl:9,hl+:136,bg+:0,fg+:14,info:5,prompt:33,spinner:108,pointer:226,marker:235,header:33'
" ironically, solarized light bat theme looks better on solarized dark terminal theme :)
let $BAT_THEME = 'Solarized (light)'
let $FZF_PREVIEW_PREVIEW_BAT_THEME = 'Solarized (light)'
```

**Comment by felippepuhle** [comment]
Hey @phongvcao, thanks for your quick response!

Just tried to set both on `init.vim` and `.bash_profile`, but it didn't change anything... Am I missing something?

**Comment by phongvcao** [comment]
@felippepuhle are you using 256 color term or 24-bit color term? Have you tried the values for Nord from `junegunn/fzf` link above?

```vim
" values for Nord theme for junegunn/fzf
let g:fzf_preview_fzf_color_option = 'fg:#D8DEE9,bg:#2E3440,hl:#A3BE8C,fg+:#D8DEE9,bg+:#434C5E,hl+:#A3BE8C,pointer:#BF616A,info:#4C566A,spinner:#4C566A,header:#4C566A,prompt:#81A1C1,marker:#EBCB8B'
```

**Comment by phongvcao** [comment]
if you also have `fzf.vim` or `fzf` or `fzf-tmux` on your system, you should double check the `FZF_DEFAULT_OPTS` in your `.bashrc`

**Comment by felippepuhle** [comment]
24-bit... removing `set termguicolors` seems to help a little but I need it for other plugins. 

Yeah, I already checked... `FZF_DEFAULT_OPTS` is empty, and setting `g:fzf_preview_fzf_color_option` with Nord theme values doesn't change anything.

**Comment by yuki-yano** [comment]
fzf-preview gets the `FZF_PREVIEW_PREVIEW_BAT_THEME` environment variable in the preview script.
https://github.com/yuki-ycino/fzf-preview.vim/blob/2503f7de63e4e75be5bbda6ce39ab73a66f6f3d5/bin/preview_fzf_grep#L9

It works in my environment, but it may not work well due to a combination of environment variables
(I had similar problems before due to differences in the development environment.)

Is it possible to add `print(bat_theme)` to the running preview script to see what it shows?

It would be helpful if you could also check the results of running `echo &shell` and `echo $SHELL` on the vim.

**Comment by felippepuhle** [comment]
Sure, here it is:

print(bat_theme) = Nord
echo &shell = /bin/zsh
echo $SHELL = /bin/zsh

**Comment by felippepuhle** [comment]
Theme seems to be the correct one, but colors are slightly different (seems to saturated)...

Highlight colors seems to be wrong compared to what I get from `yats` and  `vim-jsx-improve` but I think I can adjust it later using `g:fzf_preview_fzf_color_option`

**Comment by yuki-yano** [comment]
I checked again, the colors seem to be different in my environment. (I also use Nord.)
I'm not sure exactly how the shell works in Neovim, so it may be difficult to resolve it now. Sorry.

It seems to change the color in `:terminal`, not just in fzf-preview.

`$ ls -1 src/coc.ts | fzf --preview='bat --color=always --theme=Nord --plain {1}'`

![スクリーンショット 2020-07-29 21 44 23](https://user-images.githubusercontent.com/5423775/88801946-5ca11d00-d1e5-11ea-821e-3993a99e97b9.png)
![スクリーンショット 2020-07-29 21 44 10](https://user-images.githubusercontent.com/5423775/88801960-60cd3a80-d1e5-11ea-95d5-9ffeb7803f49.png)

**Comment by yuki-yano** [comment]
Hmmm, it seems to work fine in vim popup win.

**Comment by yuki-yano** [comment]
The top is vim and the bottom is neovim
![スクリーンショット 2020-07-29 22 21 12](https://user-images.githubusercontent.com/5423775/88805301-eeab2480-d1e9-11ea-91dd-03c3ac2a690c.png)

**Comment by yuki-yano** [comment]
I've probably figured out the cause of the problem.
It seems that Neovim is unsetting the COLORTERM environment variable and bat is coloring in 256 colors.
https://github.com/neovim/neovim/issues/10836

It has been properly colored with the following changes.
```diff
$ git --no-pager diff bin/preview_fzf_grep
diff --git a/bin/preview_fzf_grep b/bin/preview_fzf_grep
index 82ff08c..51ee45a 100755
--- a/bin/preview_fzf_grep
+++ b/bin/preview_fzf_grep
@@ -45,7 +45,7 @@ seds = [
 sed = list(filter(is_installed, seds))[0]

 result = subprocess.check_output(
-    f'{cat} "{file_name}" | {sed} -n {start},{last}p', shell=True)
+    f'COLORTERM=truecolor {cat} "{file_name}" | {sed} -n {start},{last}p', shell=True)

 for index, line in enumerate(result.decode().split("\n")):
     if int(line_num) - start == index:
```

To solve this, I need to make a change to pass the COLORTERM environment variable from TypeScript to the preview script.

**Comment by yuki-yano** [comment]
edit: 
I've added to the README.
https://github.com/yuki-ycino/fzf-preview.vim/commit/31726432501669c7a021b14d51369a2b37ad3372

---

I've tried the settings and this seems to work without any changes to the code.
Please see if this solves the problem

```vim
augroup fzf_preview
  autocmd!
  autocmd User fzf_preview#initialized call s:fzf_preview_settings()
augroup END

function! s:fzf_preview_settings() abort
  let g:fzf_preview_grep_preview_cmd = 'COLORTERM=truecolor ' . g:fzf_preview_grep_preview_cmd
endfunction
```

**Comment by felippepuhle** [comment]
it works! thanks!!!
