### ISSUE TITLE
fzf-preview.projectcommandgrep not found

### ISSUE THREAD

**Issue by ToSeven** [yuki-yano/fzf-preview.vim#164]
Is **fzf-preview.projectcommandgrep** not supported at latest version？
![image](https://user-images.githubusercontent.com/14891443/88902584-fd92e500-d284-11ea-9507-d636697a8c0f.png)

**Comment by yuki-yano** [comment]
The `reload` option is no longer feasible due to the large number of features that have been implemented by greatly improving the internal data structures.
As of version 0.2.0, the command has been removed.

Sorry, please use the ProjectGrep command.

**Comment by ToSeven** [comment]
I think this feature look like better than **projectgrep**,  because it has a good appearance.  
But，anyway，thank you for your reply and contribution!
