### ISSUE TITLE
does it support coc commands and coc list?

### ISSUE THREAD

**Issue by fgheng** [yuki-yano/fzf-preview.vim#165]
## Problems summary
does it support coc commands and coc list?

### Expected
show coc commands and coc list in fzf-preview window.

### Environment Information

- fzf-preview version (package.json):

- OS:

- Vim/Neovim version: neovim

### Provide a minimal init.vim

```vim
" call plug#begin('~/.vim/plugged')
" Plug 'junegunn/fzf'
" Plug 'neoclide/coc.nvim', {'branch': 'release'}
" Plug 'ryanoasis/vim-devicons'
" call plug#end()
" 
" let g:coc_global_extensions = ['coc-fzf-preview']
```

### Dockerfile that reproduces the problem (if possible)

Refer to https://github.com/yuki-ycino/fzf-preview.vim/blob/master/.github/issue_example/Dockerfile

```Dockerfile
```

**Comment by yuki-yano** [comment]
I haven't implemented the coc list and coc commands yet because they weren't very high on my priority list.
coc-fzf implements them.

https://github.com/antoinemadec/coc-fzf/

**Comment by fgheng** [comment]
oh, thank you very much
