### ISSUE TITLE
Error occured when using projectgrep 

### ISSUE THREAD

**Issue by fgheng** [yuki-yano/fzf-preview.vim#166]
## Problems summary
Error occured when using projectgrep 

![image](https://user-images.githubusercontent.com/50551377/88996953-0fc26100-d321-11ea-8302-aef89e1554fa.png)

do you know how to config it?

**Comment by fgheng** [comment]
I know how to use it
```
CocCommand fzf-preview.ProjectGrep grep
```

**Comment by fgheng** [comment]
oh sorry, it is not right, if I use command `CocCommand fzf-preview.ProjectGrep greps it will search lines which content grep.

does projectgrep support dynamic search? just open the floating window and show results based on my in time inputing

**Comment by fgheng** [comment]
if I use CocCommand fzf-preview.ProjectGrep without parameters, errors occured just like the picture above.

**Comment by yuki-yano** [comment]
To find all the lines you can use `:FzfPreviewProjectGrep .` (Just like how to use ripgrep.)
