### ISSUE TITLE
FzfPreviewDirectoryFiles is slower than fzf.vim's Files command

### ISSUE THREAD

**Issue by fgheng** [yuki-yano/fzf-preview.vim#167]
Hello, FzfPreviewDirectoryFiles is slower than fzf.vim's Files command.

I want to find a file at my user home(~/), if I use `FzfPreviewDirectoryFiles ~/`,  the preview window will be showed after a long time.

**Comment by yuki-yano** [comment]
In fzf.vim, the result of the command is piped as it is, so it's fast.

In fzf-preview, fzf receives the result of the command and processes the data in Node (for various functions) before running fzf.
So if you need to input a lot of data at once, fzf may be slow to start.
