### ISSUE TITLE
Feature Request: fzf-tmux support

### ISSUE THREAD

**Issue by ferhaterata** [yuki-yano/fzf-preview.vim#168]
Hi, 

Would be possible if you could possibly support fzf-tmux script for launching fzf in a tmux pane?

https://github.com/junegunn/fzf#fzf-tmux-script

Thanks!

![image](https://user-images.githubusercontent.com/5862659/89700960-c8c80300-d900-11ea-899d-ed595ade6ff9.png)

**Comment by yuki-yano** [comment]
Sorry for the late reply.
Thanks. It's not a high priority, but I will consider it when I get more requests.

**Comment by pearagit** [comment]
I'm interested in a such a feature.
@ferhaterata What's the name of your colorscheme? It's very pretty, looks like a modified one dark theme

**Comment by ferhaterata** [comment]
hi @kintsugi, actually it's gruvbox bundled with spacevim (https://spacevim.org/layers/colorscheme/)

I use kde's konsole terminal with Gruvbox colorscheme; that of vifm is set gruvbox too.

**Comment by yuki-yano** [comment]
I tried it, but it was very unstable, so I think I will not implement it now.
I will try it periodically, and if it is stable in my environment, I will implement it.
