### ISSUE TITLE
how to close float window 

### ISSUE THREAD

**Issue by MaxJohnXiang** [yuki-yano/fzf-preview.vim#169]
## Problems summary

 when abort search and input <Esc> , the float window still not exist . 
### Environment Information

- fzf-preview version (package.json): coc-fzf-preview

- OS: mac os 

- Vim/Neovim version:

### Provide a coc-fzf-preview init.vim

```vim
" call plug#begin('~/.vim/plugged')
" Plug 'junegunn/fzf'
" Plug 'neoclide/coc.nvim', {'branch': 'release'}
" Plug 'ryanoasis/vim-devicons'
" call plug#end()
" 
" let g:coc_global_extensions = ['coc-fzf-preview']
```

### Screenshot

![image](https://user-images.githubusercontent.com/24894004/89722234-cf966900-da19-11ea-9b8d-dfac674e033f.png)

**Comment by MaxJohnXiang** [comment]
![image](https://user-images.githubusercontent.com/24894004/89726703-27e85d80-da50-11ea-9856-370787672f6c.png)

**Comment by yuki-yano** [comment]
Sorry for the late reply.

Due to the specifications of coc.nvim, typing quickly before the window comes up can cause problems.
If the problem occurs even if you type after the window appears, please report again.
