### ISSUE TITLE
Some of FzfPreviewProject... series don't properly resolve filepath when in sub-directory of project root.

### ISSUE THREAD

**Issue by LumaKernel** [yuki-yano/fzf-preview.vim#170]
## Problems summary

```
.  <--  project root
├── .git/
├── a.txt
└── x/   <-- pwd is here
    └── b.txt
```

Some of `:FzfPreviewProject...` series, say `:FzfPreviewProjectMrwFiles`, settle filepath from `pwd`, so when selected `x/b.txt` it is resolved as `./x/x/b.txt` .
`bat` is saying error in preview window and get new buffer pointing `./x/x/b.txt` after selecting by hitting enter.
Others like `:FzfPreviewProjectFiles` are not the case.

### Expected

Paths sharing with `pwd` is omitted. For above instance, `./x/b.txt` is resolved.

### Environment Information

- fzf-preview version (package.json): latest (0.4.9)

- OS: Ubuntu 18.04

- Vim/Neovim version: neovim HEAD

### Provide a minimal init.vim

```
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', {'dir': '~/.fzf', 'do': './install --all'}
Plug 'yuki-ycino/fzf-preview.vim', {'do': 'yarn'}
call plug#end()
```

Please refer to the Dockerfile.

### Screenshot

![image](https://user-images.githubusercontent.com/29811106/90282896-1f59b200-deaa-11ea-85e3-24b069f0407d.png)

(off-topic: that `-`  is not rendered is windows-terminal issue maybe or my font-size is too small)
(Error of  `sh:  1:  [[...` is another issue. I see that with other commands in which this issue is not happened.)

### Dockerfile that reproduces the problem (if possible)

Top of lines are little modified ( installing yarn and neovim, install this plugin as remote-plugin ).

```Dockerfile
FROM ubuntu:bionic

# Neovim
RUN apt-get update && apt install -y ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip git

WORKDIR /usr/local/src
RUN git clone https://github.com/neovim/neovim.git

WORKDIR /usr/local/src/neovim
RUN make && make install

# Node
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt install -y nodejs
RUN npm install -g yarn neovim

# Python
RUN apt install -y python

# bat
RUN curl -LO https://github.com/sharkdp/bat/releases/download/v0.15.4/bat_0.15.4_amd64.deb
RUN dpkg -i bat_0.15.4_amd64.deb

# ripgrep
RUN curl -LO https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
RUN dpkg -i ripgrep_11.0.2_amd64.deb

# vim plugin
RUN sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
RUN mkdir -p /root/.config/nvim
RUN echo "call plug#begin('~/.vim/plugged') \n\
Plug 'junegunn/fzf', {'dir': '~/.fzf', 'do': './install --all'} \n\
Plug 'yuki-ycino/fzf-preview.vim', {'do': 'yarn'} \n\
call plug#end() \n\
\n" >> /root/.config/nvim/init.vim

RUN nvim +PlugInstall +UpdateRemotePlugin +qa!



# REPRODUCING STEPS

RUN mkdir /usr/local/work -p
WORKDIR /usr/local/work

RUN git init
RUN echo a > a.txt
RUN mkdir x
RUN echo b > x/b.txt

WORKDIR /usr/local/work/x
RUN nvim b.txt +"normal ofrom dockerfile" +wq

ENTRYPOINT ["/bin/bash"]

# run nvim, :FzfPreviewProjectMrwFiles and select x/b.txt
```

**Comment by yuki-yano** [comment]
Sorry for the late reply.

Fixed: https://github.com/yuki-ycino/fzf-preview.vim/commit/d61b3c1b583417514549a700b9b2365f595b9384
Please check.

**Comment by LumaKernel** [comment]
Nice. Seems fine. Thank you!
