### ISSUE TITLE
ProjectGrep '5 q' prefix to first match's filename

### ISSUE THREAD

**Issue by fedoranvar** [yuki-yano/fzf-preview.vim#171]
## Problems summary

Good day to you!

 I'm running "CocCommand fzf-preview.ProjectGrep <word>" and it occurs that first match's filename prepended with '5 q' prefix, and so I can't open file that I want.

Thank you!
### Expected

No prefix in result matches.

### Environment Information

- fzf-preview version (package.json): 0.4.9

- OS: Ubuntu 20.04

- Vim/Neovim version: Neovim 0.4.3

### Provide a minimal init.vim

```vim
    call plug#begin()
    Plug 'itchyny/lightline.vim'
    Plug 'mengelbrecht/lightline-bufferline'
    Plug 'christoomey/vim-tmux-navigator'
    Plug 'scrooloose/nerdcommenter'
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
    Plug 'voldikss/vim-floaterm'
    Plug 'easymotion/vim-easymotion'
    Plug 'ryanoasis/vim-devicons'
    Plug 'puremourning/vimspector'
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
    Plug 'yuki-ycino/fzf-preview.vim', { 'branch': 'release', 'do': ':UpdateRemotePlugins' }
    Plug 'antoinemadec/coc-fzf'
    Plug 'morhetz/gruvbox'
    call plug#end()

```

### Screenshot
![image](https://user-images.githubusercontent.com/52028706/90374955-b894ee00-e08d-11ea-922b-97f3e9d4fbaa.png)

### Dockerfile that reproduces the problem (if possible)

Refer to https://github.com/yuki-ycino/fzf-preview.vim/blob/master/.github/issue_example/Dockerfile

```Dockerfile
```

**Comment by fedoranvar** [comment]
also found that at GitStatus 
![image](https://user-images.githubusercontent.com/52028706/90382291-00b90e00-e098-11ea-9140-a5508ba3337b.png)

**Comment by fedoranvar** [comment]
I've had set FZF_DEFAULT_COMMAND = 'rg --hidden --files'

This issue was resolved by deleting this line.

Thanks!

**Comment by fedoranvar** [comment]
also in GitStatus

![image](https://user-images.githubusercontent.com/52028706/90721440-3a755900-e2d2-11ea-9c51-ab24405c2bfc.png)

**Comment by yuki-yano** [comment]
Sorry for the late reply.

I can't reproduce it well in my hand, but would removing the other plugins cause this problem?

**Comment by fedoranvar** [comment]
found the issue:
```
 set shellcmdflag=-ic
```
