### ISSUE TITLE
Feature request: a way to open quickly the same last action 

### ISSUE THREAD

**Issue by felippepuhle** [yuki-yano/fzf-preview.vim#172]
Hey, how is it going?

I was wondering if there's a way we can open quickly the same last action I executed.

For example, imagine I'm refactoring some code on my project and I used `[fzf-p]gr`, then searched for some keyword.
The preview would show some files, I open the first one, change what I need to change and I want to open the preview again with the same keyword, but with the list updated.

Does it make sense?

I have no idea if there's a way to do it, but I can help with what is needed if so.

Thanks!

**Comment by yuki-yano** [comment]
Sorry for the delay in replying.

It's not impossible to implement, but there needs to be a change to save all executions.
The cost is high, so let it be a future issue.

Restoring the query can be done by using the --resume option.

**Comment by felippepuhle** [comment]
It works pretty well for the resources:

```
nnoremap <silent> [fzf-p]pr    :<C-u>CocCommand fzf-preview.FromResources project_mru git --resume<CR>
```

But it's not working for grep:

```
nnoremap          [fzf-p]grr   :<C-u>CocCommand fzf-preview.ProjectGrep --resume<Space>
```

![Screen Shot 2020-09-09 at 3 07 42 PM](https://user-images.githubusercontent.com/15961929/92636794-50ad7e00-f2ae-11ea-8bc3-e8898a6260b2.png)

Am I doing something wrong?

Thanks!!!

**Comment by yuki-yano** [comment]
ripgrep prints an error if you don't enter a search target.
For example, if you want to search the entire project, you should use `:CocCommand fzf-preview.ProjectGrep . --resume`

**Comment by optimistiks** [comment]
I'm having the same issue. Sorry if I'm missing something obvious here.
So I have two bindings defined

```
" Search text everywhere
noremap <F2> :CocCommand fzf-preview.ProjectGrep<Space>
" Reuse the input that was last used to select the element with fzf.
" Do not need to pass a value for this option.
nnoremap <Leader>G :<C-u>CocCommand fzf-preview.ProjectGrep --resume<Space>
```

I press F2, then search query, then Enter - it works fine, it opens the preview window with search results.
Then I open one of the search results, the preview window closes.
Then I press Leader + G, then Enter, it shows the same error as on the screenshot in the above message.
If I use `:CocCommand fzf-preview.ProjectGrep . --resume`, it just opens the whole project in the preview window, without any search query at all.

I use the latest version of coc and coc-fzf-preview.

**Comment by yuki-yano** [comment]
There is currently no way to automatically pass a similar query to grep as before.
The "resume" option is a feature that allows you to enter queries entered during the last fzf run when it starts.

**Comment by loyd** [comment]
Still no solution?
I've migrated from LeaderF, where this feature works perfectly (`LeaderfRgRecall`) and now I'm realizing that it's a killer feature.

**Comment by yuki-yano** [comment]
Implemented GrepRecall on a trial basis.
Please give it a try.
https://github.com/yuki-yano/fzf-preview.vim/pull/266
