### ISSUE TITLE
Use "highlight" instead of "bat"?

### ISSUE THREAD

**Issue by phongvcao** [yuki-yano/fzf-preview.vim#173]
Is there a way I can use [Highlight](http://www.andre-simon.de/doku/highlight/en/highlight.php) as the highlight program instead of `bat`? In [the official FZF doc](https://github.com/junegunn/fzf#preview-window) I can use either `cat`, `bat` or `highlight`, but I'm not sure how to use `highlight` here in fzf-preview.vim?

**Comment by phongvcao** [comment]
Specifically, right now I'm having these lines in my `.vimrc`:

```vim
let g:fzf_preview_command = 'cat --number'
let g:fzf_preview_lines_command = 'cat --number'
```

but when I tried these lines, it didn't work. `fzf-preview.vim` still uses cat:

```vim
let g:fzf_preview_command = 'highlight'
let g:fzf_preview_lines_command = 'highlight'
```

What did I do wrong?

FYI, `highlight` is available on Ubuntu through `apt-get`:

```
sudo apt-get install highlight
```

and Mac OS X through Homebrew:

```
brew install highlight
```

**Comment by yuki-yano** [comment]
I've looked at highlighting and it looks like I'd be better off using bat.
It looks like you need to specify the options to use highlight, but I didn't find the right setting right away.
