### ISSUE TITLE
Vim sometimes freezes when I select a file

### ISSUE THREAD

**Issue by lynndylanhurley** [yuki-yano/fzf-preview.vim#176]
## Problems summary
Vim occasionally freezes when I select a file.

### Expected
The file should open, vim should not freeze.

### Environment Information

- fzf-preview version (package.json):
`0.4.9`

- OS:
MacOS

- Vim/Neovim version:
Neovim HEAD

### Screenshot

<img width="1243" alt="Screen Shot 2020-09-03 at 3 08 21 PM" src="https://user-images.githubusercontent.com/468037/92162150-50693a80-edf7-11ea-8469-b98d26d7cd46.png">

**Comment by lynndylanhurley** [comment]
Sometimes the fzf-preview window will partially disappear before freezing (attached)
<img width="2435" alt="Screen Shot 2020-09-03 at 5 26 59 PM" src="https://user-images.githubusercontent.com/468037/92179693-cd51df80-ee0a-11ea-83fd-2263fc575325.png">

**Comment by yuki-yano** [comment]
Hmmm, it may be difficult to confirm without reproducibility.
Are you using coc extensions or remote plugin?

**Comment by lynndylanhurley** [comment]
Yes I am using coc, but I don't think I'm using the coc extensions for this project. Is this a known coc issue?

Here's my relevant fzf-preview config:
```vim
nnoremap <silent> <Leader>t :FzfPreviewFromResources project_mru git<CR>
nnoremap <silent> <Leader>b :FzfPreviewFromResources buffer<CR>
nnoremap <Leader>/ :FzfPreviewProjectGrep .<CR>
xnoremap <Leader>/ "sy:FzfPreviewProjectGrep<Space>-F<Space>"<C-r>=substitute(substitute(@s, '\n', '', 'g'), '/', '\\/', 'g')<CR>"
```

**Comment by lynndylanhurley** [comment]
Update: the issue occurs when using the standard fzf without this plugin. Will update if I figure out the cause.

**Comment by lynndylanhurley** [comment]
Found the issue. This was somehow caused by the [quick-scope](https://github.com/unblevable/quick-scope) plugin.

Not sure why exactly, but disabling quick-scope resolved the issue completely.

**Comment by yuki-yano** [comment]
OK. Thanks.
