### ISSUE TITLE
Don't show fzf preview on Windows 10

### ISSUE THREAD

**Issue by vikei** [yuki-yano/fzf-preview.vim#177]
## Problems summary
When open fzf preview preview showing for 1 second and close. In `:messages` displays error
`[coc.nvim] Command: fzf-preview-callback.OpenFileUndefined not found`

Video: https://streamable.com/ju89bw

### Expected

Show preview with files.

### Environment Information

- fzf-preview version (package.json): _where to look?_

- OS: Windows 10

- Vim/Neovim version:
C:\Users\vitalikh>nvim --version
NVIM v0.5.0-695-gf34eeba2d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Provide a minimal init.vim

```vim
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'yuki-ycino/fzf-preview.vim', { 'branch': 'release', 'do': ':UpdateRemotePlugins' }
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install() } }
let g:coc_global_extensions = [
\ 'coc-fzf-preview',
\ ]


" coc-fzf-preview
nmap <leader>fp :call CocAction('runCommand', 'fzf-preview.ProjectFiles')<CR>
" open buffers list
nmap <leader>fb :call CocAction('runCommand', 'fzf-preview.Buffers')<CR>
" last written
nmap <leader>fw :call CocAction('runCommand', 'fzf-preview.MrwFiles')<CR>
" last used
nmap <leader>fu :call CocAction('runCommand', 'fzf-preview.ProjectMruFiles')<CR>
" marks
nmap <leader>fm :call CocAction('runCommand', 'fzf-preview.Marks')<CR>
" jumps
nmap <leader>fm :call CocAction('runCommand', 'fzf-preview.Jumps')<CR>
" last changes
nmap <leader>flc :call CocAction('runCommand', 'fzf-preview.Changes')<CR>
" git actions
nmap <leader>fga :call CocAction('runCommand', 'fzf-preview.GitActions')<CR>
" look references on cursor
nmap <leader>fr :call CocAction('runCommand', 'fzf-preview.CocReferences')<CR>
" project diagnostic
nmap <leader>fdp :call CocAction('runCommand', 'fzf-preview.CocDiagnostics')')<CR>
" current file diagnostic
nmap <leader>fcd :call CocAction('runCommand', 'fzf-preview.CocCurrentDiagnostics')')<CR>

```

**Comment by yuki-yano** [comment]
I'm sorry, but I haven't been able to verify that it works on windows.
Because fzf itself seems to be incompatible with windows, please let me be out of support.

**Comment by vikei** [comment]
If I run `:FZF` it works
![image](https://user-images.githubusercontent.com/55663427/93736533-56c62780-fbe9-11ea-884c-cada7fd81a6c.png)

**Comment by yuki-yano** [comment]
Hmmm, for example, fzf-preview uses Node to implement things like file system access.
It may be that the problem is occurring because it doesn't take Windows into account when doing so.
I don't have a Windows environment at hand, so it's difficult to verify those things. My apologies.

**Comment by vikei** [comment]
Understood. Thank you
