### ISSUE TITLE
[coc.nvim] Command error: request error nvim_call_function - Vim(call):E117: Unknown function: fzf#run

### ISSUE THREAD

**Issue by kaka-ruto** [yuki-yano/fzf-preview.vim#178]
## Problems summary
I followed the coc installation instructions, and even removed the initial version installed using Vim Plug.

The error comes up when I invoke any of the coc commands, eg `CocCommand fzf-preview.GitStatus`

It worked the first time, then I tried changing the default mapping <leader>f to something else then weirdly enough it started throwing the error, even when I changed it back to <leader>f. It sounds weird, I believe this is not the cause of the error

### Expected
It should open a floating window

### Environment Information

- fzf-preview version (package.json):
0.4.12

- OS:
Mac OS High Sierra

- Vim/Neovim version:
0.4.4

### Provide a minimal init.vim

```vim
" call plug#begin('~/.vim/plugged')
" Plug 'junegunn/fzf'
" Plug 'neoclide/coc.nvim', {'branch': 'release'}
" Plug 'ryanoasis/vim-devicons'
" call plug#end()
" 
" let g:coc_global_extensions = ['coc-fzf-preview']
```

### Screenshot
![Screen Shot 2020-09-21 at 20 00 06](https://user-images.githubusercontent.com/16320124/93797737-4ba0e500-fc45-11ea-9e8b-a66f77b9a8ae.png)

### Dockerfile that reproduces the problem (if possible)

Refer to https://github.com/yuki-ycino/fzf-preview.vim/blob/master/.github/issue_example/Dockerfile

```Dockerfile
```

**Comment by yuki-yano** [comment]
The reason why fzf#run is not found is because the fzf plugin failed to install.
Please check about the installation of 'junegunn/fzf'.

**Comment by kaka-ruto** [comment]
Thanks @yuki-ycino , I fixed it by installing the fzf plugin like so `Plug 'junegunn/fzf.vim' | Plug '/usr/local/opt/fzf'`

Is it something we might want to add to the readme?

**Comment by yuki-yano** [comment]
This option should install fzf, so it's not necessary.
`Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }`
