### ISSUE TITLE
CocCommand fzf-preview.ProjectGrep command fails when input contains spaces

### ISSUE THREAD

**Issue by acepukas** [yuki-yano/fzf-preview.vim#179]
## Problems summary

CocCommand fzf-preview.ProjectGrep command fails when input contains spaces. The issue is that the `--header='[Grep from] ...'` option is single quoted. I tested out with double quotes by editing line 36627 in `lib/index.js` just to verify that it was the problem and it seems to be. Whether or not that would have implications elsewhere, I can't say.

### Expected

If grep command input contains spaces the `--header` option should be something like `--header="[Grep from] 'some text'"` and not `--header='[Grep from] 'some text''`. Either that or the quotes should be the other way around, as long as the same type of quotes aren't used to delimit each span of text. As it stands now, the plugin will single quote input if it contains spaces.

### Environment Information

- fzf-preview version (package.json): 0.4.12

- OS: Arch Linux

- Vim/Neovim version: 0.4.4

**Comment by yuki-yano** [comment]
The search with spaces is working in my environment.
Can you give me an example of how it actually fails?
![スクリーンショット 2020-09-22 14 27 44](https://user-images.githubusercontent.com/5423775/93846761-f1a12d80-fcdf-11ea-8597-227214fc003f.png)

**Comment by acepukas** [comment]
I see. I hadn't expected to have to quote the input myself if there are
spaces. fzf.vim's functionality was slightly different. I tested it the way
you demonstrated and that works. No problem then.
