### ISSUE TITLE
Fzf* commands are not found

### ISSUE THREAD

**Issue by bram2000** [yuki-yano/fzf-preview.vim#180]
## Problems summary
When trying to run any of the Fzf* commands (e.g. `:FzfPreviewProjectFiles`) I get the error `Not an editor command: FzfPreviewProjectFiles`.

### Expected
I would expect the same as running `:CocCommand fzf-preview.ProjectFiles` which does seem to work.

### Environment Information

- fzf-preview version (package.json):
```
  File: package.json
  {
    "dependencies": {
      "coc-fzf-preview": ">=0.4.15",
      "coc-python": ">=1.2.12",
      "coc-snippets": ">=2.2.1"
    }
  }
```

- OS:
MacOS 10.14.6

- Vim/Neovim version:
Neovim v0.4.4

**Comment by yuki-yano** [comment]
Due to the specifics of adding commands to coc extensions, regular commands are not supported in coc.
Please use CocCommand.
