### ISSUE TITLE
Matching color schemes

### ISSUE THREAD

**Issue by ldelossa** [yuki-yano/fzf-preview.vim#183]
## Problems summary
I'd like some configuration option similar to fzf-vim for matching the fzf color scheme to vim's current.

```

" Customize fzf colors to match your color scheme
" - fzf#wrap translates this to a set of `--color` options
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }
```

In this dictionary, fzf color scheme will always match vim's. Is this possible?

### Expected
A config option existed to keep fzf and vim color scheme in sync.

### Environment Information

- fzf-preview version (package.json): HEAD

- OS: Fedora 32

- Vim/Neovim version: Vim 8

### Provide a minimal init.vim

```vim
" call plug#begin('~/.vim/plugged')
" Plug 'junegunn/fzf'
" Plug 'neoclide/coc.nvim', {'branch': 'release'}
" Plug 'ryanoasis/vim-devicons'
" call plug#end()
" 
" let g:coc_global_extensions = ['coc-fzf-preview']
```

### Dockerfile that reproduces the problem (if possible)

Refer to https://github.com/yuki-ycino/fzf-preview.vim/blob/master/.github/issue_example/Dockerfile

```Dockerfile
```

**Comment by yuki-yano** [comment]
I've read the code.
To implement it in fzf-preview, I need the local functions used in fzf.
https://github.com/junegunn/fzf/blob/c60ed1758315f0d993fbcbf04459944c87e19a48/plugin/fzf.vim#L272-L289

I'm going to put out a PR that exposes the function.

**Comment by yuki-yano** [comment]
If you use reflection, I have confirmed that this code works, but you do so at your own risk.
If the fzf code is changed, it will not work.

```vim
augroup fzf_preview
  autocmd!
  autocmd User fzf_preview#initialized call s:fzf_preview_settings()
augroup END

function! FzfColor()
  if !exists('g:fzf_colors')
    return ''
  endif

  let lines = filter(split(execute('script'), '\n'), { _, v -> v =~# 'junegunn/fzf/plugin/fzf.vim' })
  if len(lines) < 1
    return ''
  endif

  let file_nums = matchlist(lines[0], '^\s*\(\d\+\)')
  if len(file_nums) <= 1
    return ''
  endif

  let func_name = "\<SNR\>" . file_nums[1] . '_defaults()'
  if !exists('*' . func_name)
    return ''
  endif

  let option = matchlist(execute('echo ' . func_name), '''--color=\(.\+\)''')
  if len(option) <= 1
    return ''
  endif

  return option[1]
endfunction

let g:fzf_colors = {
\ 'fg':      ['fg', 'Normal'],
\ 'bg':      ['bg', 'Normal'],
\ 'hl':      ['fg', 'Comment'],
\ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
\ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
\ 'hl+':     ['fg', 'Statement'],
\ 'info':    ['fg', 'PreProc'],
\ 'border':  ['fg', 'Ignore'],
\ 'prompt':  ['fg', 'Conditional'],
\ 'pointer': ['fg', 'Exception'],
\ 'marker':  ['fg', 'Keyword'],
\ 'spinner': ['fg', 'Label'],
\ 'header':  ['fg', 'Comment']
\ }

function! s:fzf_preview_settings() abort
  let g:fzf_preview_fzf_color_option = FzfColor()
endfunction
```

**Comment by ldelossa** [comment]
@yuki-ycino what do you mean by this:  
> If the fzf code is changed, it will not work.

Also I noticed if I use the following "colors" array, it seems to just utilize the term's defaults. 

```
let g:fzf_preview_fzf_color_option = 'fg:-1,bg:-1,hl:-1,fg+:-1,bg+:-1,hl+:-1,info:-1,marker:-1,header:-1'
```

maybe my request here is actually not necessary?

**Comment by yuki-yano** [comment]
This code relies on an internal implementation of fzf, so it may not work if the code in the fzf repository is changed.

You can use `g:fzf_preview_fzf_color_option` to pass options to fzf-preview, but it may not work if you're using termguicolors or something similar.

**Comment by yuki-yano** [comment]
If it is resolved, I will close it once.
I'll consider implementing it when the need arises.
