### ISSUE TITLE
Search (Grep text under cursor) in current file

### ISSUE THREAD

**Issue by fedoranvar** [yuki-yano/fzf-preview.vim#186]
## Problems summary

I want to be able quickfix only current file (or All Buffers) or search-jump in current-file (or All Buffers) by selected (visual mode) text

Is there any way to pass path (to file) to ProjectGrep or text to Lines (BufferLines)?

(imho Lines would be better)

### Expected

I can do this functionality:

- * by using ProjectGrep and input path to file (but still it greps in all files from root folder, so in large projects it gets slower)
- * by using Lines and copy-paste selected text ( but still it loads all file lines, so in large files it gets slower)

I expect to pass selected text (via visual), press keybinding 
` vnoremap [fzf-p]/ "+y:CocCommand fzf-preview.Lines (BufferLines) <C-r>+<CR>
`
and see only those lines that contains selected text

### Environment Information

- fzf-preview version (package.json):

- OS: Arch

- Vim/Neovim version: Neovim

### Provide a minimal init.vim

```vim
" call plug#begin('~/.vim/plugged')
" Plug 'junegunn/fzf'
" Plug 'neoclide/coc.nvim', {'branch': 'release'}
" Plug 'ryanoasis/vim-devicons'
" call plug#end()
" 
" let g:coc_global_extensions = ['coc-fzf-preview']
```

**Comment by yuki-yano** [comment]
Does this setup solve the problem?
`xnoremap <silent> [fzf-p]/ "sy:<C-u>CocCommand fzf-preview.Lines --add-fzf-arg=--query="<C-r>=substitute(@s, '\(^\\v\)\\|\\\(<\\|>\)', '', 'g')<CR>"<CR>`

**Comment by fedoranvar** [comment]
yes, it does.

Thank you!
