### ISSUE TITLE
[Feat] Custom buffer tags command

### ISSUE THREAD

**Issue by AdrienLemaire** [yuki-yano/fzf-preview.vim#187]
The current tags command [doesn't seem to be customizable](https://github.com/yuki-ycino/fzf-preview.vim/blob/6b2b7118e41ced337ae16a92544e624c8755597e/src/const/system.ts#L1), and will fail to load tags for some filetypes like typescripreact

I could get my tags loaded by modifying the `~/.config/coc/extensions/node_modules/coc-fzf-preview/lib/index.js` file as follow:
```diff
- exports.BUFFER_TAGS_COMMAND = "ctags -f - --sort=yes --excmd=number";
+ exports.BUFFER_TAGS_COMMAND = "ctags -f - --languages=typescript --langmap=typescript:.ts.tsx --sort=yes --excmd=number";
```
It would be great if we could define this in our vimrc
```vim
augroup typescriptreact "{{{
    autocmd!
    " autocmd FileType typescript.tsx,typescriptreact let g:buffer_tags_command = 'tstags -f-'
    autocmd FileType typescript.tsx,typescriptreact let g:buffer_tags_command = 'ctags -f - --languages=typescript --langmap=typescript:.ts.tsx --sort=yes --excmd=number'
augroup end "}}}
```

**Comment by yuki-yano** [comment]
Thank you.
I'll try to make it configurable when I have time.

**Comment by yuki-yano** [comment]
Sorry for the delay.

I just checked, and I think the latest ctags support TypeScript by default.
Could you try that first?

**Comment by AdrienLemaire** [comment]
Hi @yuki-ycino and thanks for the reply.
It looks like the arch linux package is quite outdated, so [I asked about that in their forum](https://bbs.archlinux.org/viewtopic.php?pid=1949426#p1949426). Wait and see.

**Comment by yuki-yano** [comment]
Or can't you work around it by writing the configuration in `~/.ctags.d/config.ctags`?

**Comment by AdrienLemaire** [comment]
@yuki-ycino I tried building the latest ctags version, and it doesn't support typescriptreact out of the box. 

Adding `--map-TypeScript=+.tsx` in `~/.ctags.d/config.ctags` seems to have done the trick.

**Comment by yuki-yano** [comment]
Thank you.
I'm going to close this since it seems to have been resolved.
