### ISSUE TITLE
Git ignore

### ISSUE THREAD

**Issue by ItsNilDev** [yuki-yano/fzf-preview.vim#188]
## Problems summary
Just want to add git ignore option . because it's takes at least 5 seconds to load all files. and I also want to ignore hidden files

**Comment by yuki-yano** [comment]
Couldn't this be improved by setting `g:fzf_preview_filelist_command`?

**Comment by yuki-yano** [comment]
For example, try using fd.
`let g:fzf_preview_filelist_command = 'fd'`

**Comment by ItsNilDev** [comment]
I'm seeing fzf , it searchs between for example 4,000 files, but in fzf-preview it's something like 132,000 files
including git files, hidden files , etc. so I want to ignore git files and ignore hidden files. How can I do that?
EDIT:
I also use CocCommand , is this cause the issue, I mean the loadup issue?
This command `:CocCommand fzf-preview.DirectoryFiles`

**Comment by yuki-yano** [comment]
Doesn't the fd command ignore hidden files and .gitignore by default?
`$ fd --type=file` and I've been able to ignore it.

If you are using `DirectoryFiles`, set `g:fzf_preview_directory_files_command`.

I've confirmed that the following configuration works for me.
`let g:fzf_preview_directory_files_command = 'fd --type=file .' `

**Comment by ItsNilDev** [comment]
when I put `let g:fzf_preview_directory_files_command = 'fd --type=file .'` this line into my init.vim it showed me zero files
Oh wait , I must install this command first , It couldn't find the command
