### ISSUE TITLE
Support fish shell

### ISSUE THREAD

**Issue by mredaelli** [yuki-yano/fzf-preview.vim#19]
I'm a fish shell user, and when I invoke, for instance, `FzfPreviewProjectFiles` I get:
```
~      ╭──────────────────────────────────────────────────────────────────────────────╮        
~      │ ProjectFiles>                         ┌────────────────────────────────────┐ │        
~      │   375/375                             │ fish: $(...) is not supported. In  │ │        
~      │ > ./lari/pipelines/env: No such fil.. │ [[ "$(file --mime './lari/pipeline │ │        
~      │   scrapy.cfg                          │     ^                              │ │        
~      │   setup.py                            │ [bat error]: '2)': No such file or │ │        
~      │   filters_script.py                   │                                    │ │ 
```

`nvim` is set up to use good old `bash` for shell: `:echo &shell` returns `/usr/bin/env bash`.

Is there something I'm missing or that I can do?

**Comment by yuki-yano** [comment]
I installed fish but no error occurred in my environment.
What is the value of `g:fzf_preview_filelist_command` and the execution result of that command?

**Comment by mredaelli** [comment]
I get `rg --files --hidden --follow --glob "!.git/*"`, and the output from shell starts with:
```
crawlers on  616-elcom [⇡$?] took 30s 
❯ rg --files --hidden --follow --glob "!.git/*"
./lari/pipelines/env: No such file or directory (os error scrapy.cfg
setup.py
filters_script.py
out
```

**Comment by yuki-yano** [comment]
An error has occurred in the rg command.
Update the default value of the command, so please update the plugin.

Or use another command to get the file list.

**Comment by mredaelli** [comment]
I don't think that's the problem.

Fish is complaining that it doesn't know how to parse `$(...)`, and indeed I get the same with `GitFiles`: ` [[ "$(file --mime '.coveragerc')"`, which I assume comes from [here](https://github.com/yuki-ycino/fzf-preview.vim/blob/d52179060b498805d34730911927175768f3de5a/autoload/fzf_preview.vim#L266)

The question is why is fish invoked instead of bash.

But then the problems doesn't seem to be in your plugin anyway. I'll try in fzf.

**Comment by Jayphen** [comment]
What was the resolution here? I am seeing the same problem with Fish shell. I've been using fzf and rg until now without problems.

`rg --files --hidden --follow --glob "!.git/*"` returns a list of files for me.

The problem is, as suggested, that fish doesn't support the syntax `$(command)` for interpolation and instead uses `(command)`. The former syntax produces an error

**Comment by yuki-yano** [comment]
I think this line is the problem
https://github.com/yuki-ycino/fzf-preview.vim/blob/master/autoload/fzf_preview/command.vim#L2

It is difficult to propose a reliable solution because fish cannot be reproduced in my environment even if I use it

Try `set shell=bash`

**Comment by yuki-yano** [comment]
If that doesn't work, I would consider creating a configurable `[[ "$(file --mime {})" =~ binary ]]` using variables.

**Comment by arooni** [comment]
@yuki-ycino ; even with set shell=bash; i see things like:

fish: Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.                
when doing :FZFPreviewAllBuffers

**Comment by brandoncc** [comment]
I was able to fix this by adding the following to my config:

```
" Since fish shell is the system default, nvim has all kinds of issues
" executing system() calls. Setting `shell` fixes them. fzf-preview still
" seems to use fish though, which setting $SHELL fixes.
set shell=/bin/zsh
let $SHELL = "/bin/zsh"
```
