### ISSUE TITLE
Add `!` to override

### ISSUE THREAD

**Issue by ItsNilDev** [yuki-yano/fzf-preview.vim#191]
## Problems summary

When I change something in current file, and then I want to use fzf I says I must add `!` but where to add this ?? I'm using `:CocCommand fzf-preview.DirectoryFiles`

**Comment by yuki-yano** [comment]
You can use cd, lcd, tcd, etc. or pass the path to DirectoryFiles.

**Comment by yuki-yano** [comment]
Sorry, that was another Issue.

**Comment by yuki-yano** [comment]
fzf-preview does not support bang.
You can save the file or use splits or vsplit.

**Comment by ItsNilDev** [comment]
No problem and thanks!
