### ISSUE TITLE
ProjectGrep loses file and line, has no preview

### ISSUE THREAD

**Issue by charlesnicholson** [yuki-yano/fzf-preview.vim#192]
Firstly, thank you for building fzf-preview! It's fantastic and very helpful. I don't see this issue elsewhere, so I apologize if it's my fault. Thank you in advance for reading. If I can help by debugging or experimenting, please let me know.

## Problems summary

When I issue `:FzfPreviewProjectGrep void`, The results don't have file or line numbers. The preview pane says:

```
Cannot process the entry :(
Please open an issue and describe what happened
including information such as file name and g:fzf_preview_grep_cmd
```

I'm using the remote plugin, but this also happens when I install coc and run with `:CocCommand`.

My `g:fzf_preview_grep_cmd` looks good:
```
:echo g:fzf_preview_grep_cmd
rg --line-number --no-heading --color=never
```

When I run from my terminal, I get the filenames and line numbers:
<img width="722" alt="Screen Shot 2020-11-01 at 12 05 30 PM" src="https://user-images.githubusercontent.com/3010295/97809390-8e89ab80-1c3a-11eb-9c94-68e189e20d07.png">

I looked at the fzf-preview source and saw that file and line are run with `stripAnsi`, so I tried that but it looked the same:
<img width="798" alt="Screen Shot 2020-11-01 at 12 10 32 PM" src="https://user-images.githubusercontent.com/3010295/97809508-43bc6380-1c3b-11eb-8746-86de9159af10.png">

My version of ripgrep is:
<img width="448" alt="Screen Shot 2020-11-01 at 12 07 14 PM" src="https://user-images.githubusercontent.com/3010295/97809434-d3154700-1c3a-11eb-8ff5-8e463b93dda3.png">

### Expected

I would like to see the filenames and line numbers in the search, and the contents of the file in the preview.

### Environment Information

- fzf-preview version (package.json):
```
  "name": "coc-fzf-preview",
  "version": "0.4.24",
  "description": "Dark powered fzf plugin",
  "author": "yuki-yano",
  "license": "MIT",
  "repository": {
    "url": "git@github.com:yuki-ycino/fzf-preview.vim"
  },
```

- OS:
macOS 10.15.7

- Vim/Neovim version:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/config -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/include
Compiled by brew@Catalina
```

### Provide a minimal init.vim

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'yuki-ycino/fzf-preview.vim', { 'branch': 'release', 'do': ':UpdateRemotePlugins' }
Plug 'ryanoasis/vim-devicons'
call plug#end()
```

### Screenshot
<img width="966" alt="Screen Shot 2020-11-01 at 12 00 18 PM" src="https://user-images.githubusercontent.com/3010295/97809334-3baff400-1c3a-11eb-986e-d6524b1d167f.png">

### Dockerfile that reproduces the problem (if possible)
Sorry, I don't have one yet. If it would help you please let me know and I'll try to create one.

**Comment by charlesnicholson** [comment]
Ah, sorry, this also happens if I remove the `vim-devicons` plugin.

**Comment by yuki-yano** [comment]
Thank you.
Row conversion was not working correctly when dev-icons were hidden.

Fixed: https://github.com/yuki-ycino/fzf-preview.vim/commit/b3b7ecc3d1533f12f4cdfbe895cd21b8100c7cc5
Please try 0.4.25.

**Comment by charlesnicholson** [comment]
0.4.25 fixes the issue, thanks very much for the quick fix!

<img width="1201" alt="Screen Shot 2020-11-02 at 6 44 58 AM" src="https://user-images.githubusercontent.com/3010295/97864678-fe4d7400-1cd6-11eb-90b2-11204cd9b60d.png">

**Comment by yuki-yano** [comment]
Thanks for checking it out.
And with this fix, you can now scroll the grep preview to the top of the file.

Please give it a try.

**Comment by felippepuhle** [comment]
Should the file preview auto-scroll to the highlighted line?

**Comment by yuki-yano** [comment]
Sorry, what do you mean by that?
