### ISSUE TITLE
ProjectGrep and search-filter by content (with --bind=change:reload)

### ISSUE THREAD

**Issue by fedoranvar** [yuki-yano/fzf-preview.vim#193]
## Problems summary

can't figure it out how to add --bind argument to ProjectGrep like in https://github.com/junegunn/fzf/issues/1750
to filter Grep results only in content by reloading ripgrep with filled query like in 

https://github.com/junegunn/fzf/issues/1750

![image](https://user-images.githubusercontent.com/52028706/98186966-bf672a80-1f31-11eb-9a78-c2cd38181f9a.png)

### Expected

To pass --bind argument as in example above

### Environment Information

- fzf-preview version (package.json):

- OS: Arch

- Vim/Neovim version: 0.4.4

**Comment by yuki-yano** [comment]
Sorry, fzf-preview can't handle the `reload` due to its internal implementation.
