### ISSUE TITLE
Change prompt and border=sharp

### ISSUE THREAD

**Issue by ahmadie** [yuki-yano/fzf-preview.vim#196]
use following code does not effect how border or prompt looks like,

``let g:fzf_preview_default_fzf_options = { '--border': 'sharp', '--prompt': '>> ' }``
``let $FZF_DEFAULT_OPTS="--prompt='>>'"``
``export FZF_DEFAULT_OPTS='--border=sharp --prompt=">>"'`` 

command line fzf or fzf.vim works fine though...

please advice!

**Comment by yuki-yano** [comment]
I was not aware of the Issue. Sorry about that.

I think the border is probably applied.

The prompt is overridden and applied by fzf-preview when the command is executed.
Changing this will result in a breaking change, so I'm sorry but I can't fix it.
You can use the --add-fzf-arg option to force it to be applied.

For example, `:CocCommand fzf-preview.ProjectFiles --add-fzf-arg=--prompt=">>"`
