### ISSUE TITLE
Current keymaps in fzf-p

### ISSUE THREAD

**Issue by mgabs** [yuki-yano/fzf-preview.vim#199]
I'd like to view all current key bindings in fzf-preview

function! MinExec(cmd)
  redir @a
  exec printf('silent %s',a:cmd)
  redir END
  return @a
endfunction

""" Get all mappings
function! GetMappings()
  let lines=MinExec('map')
  let lines=split(lines,'\n')
  return lines
endfunction

nnoremap <Leader>vM :call fzf#run({'source': GetMappings(),'options': '-m -n 2'} )<CR>

How do i show this in fzf-preview?

**Comment by yuki-yano** [comment]
Sorry the map display is not yet supported.
Please use fzf.vim until it is supported.
