### ISSUE TITLE
question regarding grep

### ISSUE THREAD

**Issue by burgessa23** [yuki-yano/fzf-preview.vim#2]
when using `ProjectFilesPreview` i'm able to open selected files as expected, but when using `ProjectGrepPreview` hitting enter results in a new buffer with the selected line as the title.

any ideas as to what I have mis-configured?

**Comment by yuki-ycino** [comment]
Sorry. After confirming, I was introducing https://github.com/bogado/file-line.
With this you can open a file with line number specified.

I will add it to the README later.

**Comment by yuki-ycino** [comment]
After confirming, I was introducing https://github.com/bogado/file-line .
With this you can open a file with line number specified.

I will add it to the README later.

**Comment by yuki-yano** [comment]
Sorry. After confirming, I was introducing https://github.com/bogado/file-line .
With this you can open a file with line number specified.

I will add it to the README later.

**Comment by yuki-ycino** [comment]
Sorry. After confirming, I was introducing https://github.com/bogado/file-line .
With this you can open a file with line number specified.

I will add it to the README later.

**Comment by burgessa23** [comment]
thanks!

**Comment by JensPauwels** [comment]
I'm experiencing the same behaviour even with the suggested plugin. Am I missing a configuration?

**Comment by yuki-yano** [comment]
Removed dependency on file-line plugin
