### ISSUE TITLE
Delay displaying project files when using zsh

### ISSUE THREAD

**Issue by metalelf0** [yuki-yano/fzf-preview.vim#20]
Hi, first of all, thanks for this amazing work ;)

I'm seeing a slight delay when opening the project files list. It's not anything huge, but it's noticeable (I'd say ~0.5s).

I've tried using both the `FzfPreviewProjectFiles` (which strangely also includes files under `.git` dir, but this is another issue) and `FzfPreviewGitFiles`, and I see the delay with both commands. I've also tried running the command in small projects (less than 100 files), and the delay is there, so it's not something related to the number of items, I'd guess.

I then tried disabling the highlighting in the preview pane by using `head -n 100` as the preview command, and the delay is still there.

So, I would have thought the issue is related to drawing the popup window, but the `FzfPreviewBuffers` and `FzfPreviewProjectGrep` commands don't have the delay, so I'm kinda lost.

Got any clue about what could be going on? I'm on neovim latest HEAD. Let me know if I can help anyhow.

[EDIT] Huh, forgot to add: I've ripgrep installed, obviously.

**Comment by metalelf0** [comment]
Ok, I found the culprit. It's my default shell being set to zsh. I suppose every time the plugin tries to populate the file list, it loads my whole zsh environment, which is quite slow - lot of aliases, shell prompt customization, and stuff. Running `let &shell="/usr/bin/env bash"` and using bash, which is much less customized on my system, makes the file listing appear instantaneously.

**Comment by yuki-yano** [comment]
They differ in the command they are creating to generate the list.
Is it possible to measure the time required to execute the `g:fzf_preview_filelist_command` command and the time required to execute the `g:fzf_preview_git_files_command` command?

**Comment by yuki-yano** [comment]
Since I am doing async load with heavy processing in [zinit](https://github.com/zdharma/zinit), zsh startup is very fast
It has nothing to do with this plugin, but setting it can significantly improve zsh startup time.

**Comment by lynndylanhurley** [comment]
I'm having the same issue. @metalelf0 where did you set `let &shell="/usr/bin/env bash"`?

**Comment by metalelf0** [comment]
@lynndylanhurley I set it manually in vim (via `:let ...`), but I think putting that at the end of your `.vimrc` (or `init.vim` for neovim) would be equivalent. Btw, I tried going the `zinit` route in my `.zshrc`, it's really powerful. Pretty steep learning curve, but I managed to reduce my shell startup time greatly and I don't need the `&shell` hack anymore.

**Comment by lynndylanhurley** [comment]
@metalelf0 oh nice, thanks for the tip. I'll check out `zinit` as well.

**Comment by yuki-yano** [comment]
Did you solve?
close
