### ISSUE TITLE
Q: Asynchronous results similar to fzf.vim

### ISSUE THREAD

**Issue by oddlama** [yuki-yano/fzf-preview.vim#200]
When executing `:Files` using the original [fzf.vim](https://github.com/junegunn/fzf.vim) the preview window will
open immediately and results will be populated asynchronously. This is extremely helpful when searching big directories, but `:FzfPreviewDirectoryFiles` will block until all results are available.

Can I achieve the same async behavior with fzf-preview?

**Comment by luissolanodev** [comment]
I was wondering why vim freezes whenever I try to run that command in my home directory. It would be nice to have it asynchronous too.

**Comment by yuki-yano** [comment]
fzf can receive shell commands and display the received content asynchronously when piped.
fzf-preview retrieves a list of files in TypeScript, formats them and then executes fzf.
Therefore, it is not possible to start fzf without blocking the process.
