### ISSUE TITLE
Prevent `git diff` split after GitCommit

### ISSUE THREAD

**Issue by ghost** [yuki-yano/fzf-preview.vim#204]
## Problems summary
Not problem. But I'd like to disable `:!git -C diff --cached` split after GitCommit.

### Expected

I thought it works as expected if I delete below `Git diff`, however it still pops up.

https://github.com/yuki-ycino/fzf-preview.vim/blob/b002392ed02b7d3157801b417219165139b77a39/autoload/fzf_preview/remote/consumer/git.vim#L42-L45

### Environment Information

- fzf-preview version (package.json):0.4.27

- OS:MacOS

- Vim/Neovim version:v0.4.4

### Provide a minimal init.vim

```vim
call plug#begin(s:plugdir)
	Plug 'tpope/vim-fugitive'
	Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}

	Plug 'yuki-ycino/fzf-preview.vim', { 'branch': 'release', 'do': ':UpdateRemotePlugins' }
call plug#end()
```

1. CocCommand fzf-preview.GitStatus
2. Add -> Commit

### Screenshot
<img width="612" alt="ss 1" src="https://user-images.githubusercontent.com/41639488/102412870-6b268e80-4037-11eb-95dc-8b6b21fbcdd2.png">

### Dockerfile that reproduces the problem (if possible)

none

**Comment by yuki-yano** [comment]
Currently, it is implemented to open diff windows in Fugitive and Gina respectively.
In the future, I will change the variables to change or to pass the process in Funcref.

**Comment by ghost** [comment]
Got it, fugitive's Gcommit doesn't open diff window, though.
Anyway thanks. It will be better.

**Comment by yuki-yano** [comment]
When executing commit from fzf-preview, it is intentionally implemented to display the diff before executing Git commit.
Some people may not like this, so I will consider changing it.

**Comment by ghost** [comment]
@yuki-ycino 

I see what you mean. I think that 'intended git diff' is in the code where I posted in description, right?
I look forward to your consideration.

Maybe best proposal is using 'commit --verbose', so you can see diff in one window.

**Comment by yuki-yano** [comment]
Thanks.
I'll look into it and consider modifying that policy.

**Comment by yuki-yano** [comment]
Fixed: https://github.com/yuki-ycino/fzf-preview.vim/commit/79d694f9c773b92c2ec1ba31bf57e42f43dfaffd

**Comment by ghost** [comment]
Oh what a fast and great response!
Thank you very much! I love this plugin more and more!

@yuki-ycino
