### ISSUE TITLE
blamepr zsh comand not found

### ISSUE THREAD

**Issue by 0x8f701** [yuki-yano/fzf-preview.vim#205]
## Problems summary

![image](https://user-images.githubusercontent.com/33961674/102700765-bb2c6d80-4250-11eb-9897-6a1676d0e066.png)

### Expected

no error output

### Environment Information

- fzf-preview version (package.json): `0.4.27`

- OS: `Linux Mint v19.3`

- Vim/Neovim version: `0.5-dev `

### Provide a minimal init.vim

```vim
" call plug#begin('~/.vim/plugged')
" Plug 'junegunn/fzf'
" Plug 'neoclide/coc.nvim', {'branch': 'release'}
" Plug 'ryanoasis/vim-devicons'
" call plug#end()
" 
" let g:coc_global_extensions = ['coc-fzf-preview']
```

### Dockerfile that reproduces the problem (if possible)

Refer to https://github.com/yuki-ycino/fzf-preview.vim/blob/master/.github/issue_example/Dockerfile

```Dockerfile
```

**Comment by yuki-yano** [comment]
Install the GitHub CLI command.
https://github.com/cli/cli
