### ISSUE TITLE
Question: What makes a folder a project?

### ISSUE THREAD

**Issue by cjnucette** [yuki-yano/fzf-preview.vim#22]
I can't see an option to fzf find files in a "plain" folder.
Great plugin by the way.

**Comment by 256k** [comment]
yeah i agree with you, sometimes you want to work in a project that isn't necessarity a gitepo or maybe it's just 1 folder of a big git repo project... it would be nice to have the ability to open up the folder structure... 

this could even replace nerdtree for me if it did it.

**Comment by yuki-yano** [comment]
Added FzfPreviewDirectoryFiles command. #26
Require ripgrep

**Comment by cjnucette** [comment]
Awesome, thank you!
