### ISSUE TITLE
Implement preview command for Git (Current) Logs commands

### ISSUE THREAD

**Issue by ecosse3** [yuki-yano/fzf-preview.vim#221]
Hi everyone,

I would like to say that I really love this plugin and its features compared to standard fzf.vim. I have an idea to add a feature to use [delta git](https://github.com/dandavison/delta) to view Commits and Buffer Commits diffs.

I already found implementation for fzf-preview Git Status with delta, and it would be awesome to use it with _:FzfPreviewGitLogsRpc_ and _:FzfPreviewGitCurrentLogsRpc_ at least. It could be implemented as another _preview command_. Unfortunately, I don't know lua so I cannot create PR for that.

That's the implementation for Git Status preview with delta:

```vim
let g:fzf_preview_command = 'bat --color=always --plain {-1}'
let g:fzf_preview_git_status_preview_command =
  \ "[[ $(git diff --cached -- {-1}) != \"\" ]] && git diff --cached --color=always -- {-1} | delta || " .
  \ "[[ $(git diff -- {-1}) != \"\" ]] && git diff --color=always -- {-1} | delta || " .
  \ g:fzf_preview_command
```

and it looks like this in git status:

![image](https://user-images.githubusercontent.com/17691791/104509972-c2922d00-55ea-11eb-990d-a985923786d0.png)

Thanks :)

**Comment by yuki-yano** [comment]
I'm using git show to preview the git log, but I don't know if it can be applied to delta.
I'll try it out and see if I can get it to work.
