### ISSUE TITLE
Use FzfPreviewProjectGrep without argument

### ISSUE THREAD

**Issue by ecosse3** [yuki-yano/fzf-preview.vim#222]
Hello,

I have another enhancement suggestion to add the ability to use _:FzfPreviewProjectGrep(Rpc)_ command without any arguments provided. It would work the same as in _:FzfPreviewProjectFiles(Rpc)_, so it opens a floating window and then you can start typing to search for content.

Or maybe that's possible by now? I couldn't do that with fzf-preview.

Thank you.

**Comment by yuki-yano** [comment]
To search the full text, use the `. ` as an argument.
