### ISSUE TITLE
Example using vim-which-key

### ISSUE THREAD

**Issue by farzadmf** [yuki-yano/fzf-preview.vim#227]
Hi,

Sorry that I'm not using the template, the reason is that this is not an issue but a question and ask for help.

I'm trying to set this plugin with [`vim-which-key`](https://github.com/liuchengxu/vim-which-key), and in the `README`, there are example mappings to more sophisticated commands, namely the two ones for "project grep":
```
nnoremap          [fzf-p]gr    :<C-u>CocCommand fzf-preview.ProjectGrep<Space>
xnoremap          [fzf-p]gr    "sy:CocCommand   fzf-preview.ProjectGrep<Space>-F<Space>"<C-r>=substitute(substitute(@s, '\n', '', 'g'), '/', '\\/', 'g')<CR>"
```

I don't think it's possible to use the same command using `which-key`'s _dictionary-syntax_, so for my use case, I wanted to be able to do the same thing inside a vim `function` that I create. Since I'm not an expert at all in `vimscript`, I was wondering if you can help me with that.

I can see from their documentation that I can set the mapping up separately and `which-key` would somehow "point" to that, but I'm having problems with that, and if you could help me with the custom function, it would be greatly appreciated.

This plugin is the one I cannot live without, and I have been spending A LOT of time trying to figure this out, but I couldn't.

**Comment by yuki-yano** [comment]
Sorry for the delay in replying.

Been busy lately and don't know much about which-key so at the moment I can't help.
I will take a look at which-key when I have time.
