### ISSUE TITLE
error conflict npm version to cocinstall

### ISSUE THREAD

**Issue by grimgort** [yuki-yano/fzf-preview.vim#228]
## Problems summary
error conflict npm version :

ERR! While resolving: coc-fzf-preview@2.0.8
npm ERR! Found: @types/node@14.14.21
npm ERR! node_modules/@types/node
npm ERR!   dev @types/node@"^14.14.20" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @types/node@"10.12.0" from coc.nvim@0.0.80
npm ERR! node_modules/coc.nvim
npm ERR!   coc.nvim@"^0.0.80" from the root project
npm ERR! 

### Environment Information

- fzf-preview version (package.json):

- OS: Windwos 10

- Vim/Neovim version: 0.4 neovim

**Comment by yuki-yano** [comment]
Sorry for the delay in replying.

I would like to check the version of Node you are using.

However, I can confirm that fzf-preview is currently not working properly on Windows due to another issue.
Can you please wait until #211 is completed?
