### ISSUE TITLE
Recommend vim-fetch for Neovim

### ISSUE THREAD

**Issue by tanguy-michardiere** [yuki-yano/fzf-preview.vim#23]
I spent some time trying to get file-line to work with this plugin on Neovim but couldn't. However I found another plugin that does basically the same thing and that worked out of the box on my setup: https://github.com/wsdjeg/vim-fetch
Great plugin btw

**Comment by yuki-yano** [comment]
Thank you
I'll try it when I have time and add it to the documentation.

**Comment by yuki-yano** [comment]
After some consideration, we decided to reduce our reliance on plugins.
Neither file-line plugin nor vim-fetch plugin is required for operation.
#41
