### ISSUE TITLE
Coc.nvim error when trying to use

### ISSUE THREAD

**Issue by AdamBD** [yuki-yano/fzf-preview.vim#231]
## Problems summary
Running into the following error:

`[coc.nvim] Command error: request error nvim_call_function - Vim(execute):E731: using Dictionary as a String`

### Environment Information

- fzf-preview version (package.json): latest from coc.nvim install

- OS:MacOS

- Vim/Neovim version: 0.5

**Comment by yuki-yano** [comment]
Sorry for the delay in replying.

I don't have much information and that doesn't help me to solve the problem.
Please write about the minimum settings you want to reproduce and the command you want to run.
