### ISSUE TITLE
Is it possible to change the highlight background of the cursor line?

### ISSUE THREAD

**Issue by judewang** [yuki-yano/fzf-preview.vim#235]
## Problems summary

I've chosen Dracula theme as my syntax highlight theme of `bat`. When I run `:FzfPreviewProjectGrep` and search for the keyword, the cursor line background will be the same color as one of the color from the specific theme. That made it hard to read the content of the line that matched. If I use the `:Rg` command that `fzf.vim` provided, the cursor line has different background color.

### Expected

I want to find a way to customize the highlight background of cursor line.

### Environment Information

- fzf-preview version (package.json): v2.0.8

- OS: macOS with M1 chip

- Vim/Neovim version: v0.5.0-dev+b535575

### Provide a minimal init.vim

```vim
" call plug#begin('~/.vim/plugged')
" Plug 'junegunn/fzf'
" Plug 'junegunn/fzf.vim'
" Plug 'yuki-ycino/fzf-preview.vim', { 'branch': 'release/remote', 'do': ':UpdateRemotePlugins' }
" Plug 'ryanoasis/vim-devicons'
" call plug#end()
```

### Screenshot

![CleanShot 2021-02-02 at 13 41 01](https://user-images.githubusercontent.com/1559819/106554072-fc0ce700-655d-11eb-9871-de0e07f6b709.png)
![CleanShot 2021-02-02 at 13 47 35](https://user-images.githubusercontent.com/1559819/106554074-fdd6aa80-655d-11eb-8c54-1dff4a7b7d38.png)

**Comment by yuki-yano** [comment]
The grep preview of fzf-preview uses the one specified in the FZF_PREVIEW_PREVIEW_BAT_THEME environment variable.

Do you have FZF_PREVIEW_BAT_THEME set in init.vim?

**Comment by judewang** [comment]
@yuki-yano Thank you, this solved the issue.
