### ISSUE TITLE
Disable fzf-preview cancel on <Esc>

### ISSUE THREAD

**Issue by poetaman** [yuki-yano/fzf-preview.vim#237]
## Problems summary
If I try to use up/down arrow keys or mouse scroll it closes fzf-preview window. 

### Expected
There should be a way for up/down arrow keys and mouse scroll to work (it does in original fzf plugin). Please suggest a way to disable exit on <Esc>, or remove it as a default behavior. The reason up/down keys, and mouse scroll does this because they generate "escape" sequences, and that escape cancels fzf-preview.

### Environment Information

- fzf-preview version (package.json): latest https://github.com/yuki-yano/fzf-preview.vim/commit/abeb5eee5c639c1cf48f9eb61c710c359d8c087e

- OS: macOS 11.2 ARM64

- Vim/Neovim version: Vim 8.2

**Comment by yuki-yano** [comment]
Please set `g:fzf_preview_quit_map`
