### ISSUE TITLE
Add filetype=fzfpreview to the enable changing devicons colors

### ISSUE THREAD

**Issue by poetaman** [yuki-yano/fzf-preview.vim#238]
## Problems summary
Am unable to apply custom devicons colors to fzf-preview window. The pattern of code that applies custom coloring does so by applying an autocommand FileType to certain filetypes where icons should follow custom coloring, check this: https://github.com/ryanoasis/vim-devicons/issues/158. So please add a filetype to the window that displays the file listing. Please also make sure that it is not set in the code preview subwindow of fzf-window, or else there will be a lot of slowdown.

### Expected
fzf file listing subwindow has a filetype name like 'fzfpreview', or something shorter or different that you like.

### Environment Information

- fzf-preview version (package.json): latest https://github.com/yuki-yano/fzf-preview.vim/commit/abeb5eee5c639c1cf48f9eb61c710c359d8c087e

- OS: macOS 11.2 ARM64

- Vim/Neovim version: Vim 8.2

**Comment by yuki-yano** [comment]
fzf-preview is not designed to be color changeable.
Please create a PR if necessary.
