### ISSUE TITLE
ProjectGrep unreadable with light themes

### ISSUE THREAD

**Issue by NicolaiRuckel** [yuki-yano/fzf-preview.vim#24]
When using `:FzfPreviewProjectGrep` with a light theme the text is barely readable (see screenshot).
Manually editing `bin/preview_fzf_grep` to use another colorscheme fixes that issue. Maybe a global theme option for using `bat` would be nice.
![Screenshot from 2020-02-07 15-48-49](https://user-images.githubusercontent.com/831282/74040356-d9d09f80-49c3-11ea-818b-3666701020db.png)

**Comment by metalelf0** [comment]
@NicolaiRuckel you can also do `:let g:fzf_preview_command = 'bat --color=always --style=grid --theme=GitHub {-1}'`, as stated in the readme. Sub `GitHub` with any light theme of your choice.

**Comment by NicolaiRuckel** [comment]
Thank you for your suggestion. I did this but for `FzfPreviewProjectGrep` the corresponding option is `let g:fzf_preview_grep_preview_cmd` and its default value is `expand('<sfile>:h:h') . '/bin/preview_fzf_grep'`. I tried to replace it with `bat` but this gives some errors.

**Comment by metalelf0** [comment]
Hmm, right. Guess we'll need to wait for a fix then ;)

**Comment by NicolaiRuckel** [comment]
Maybe the base16 theme would be a more sensible default?
See https://github.com/sharkdp/bat/issues/490

Actually, it doesn’t work even if you set your terminal colors in nvim.

**Comment by yuki-yano** [comment]
One workaround is to copy and rewrite the preview script to an executable location.
Set the path to `g:fzf_preview_grep_preview_cmd` and preview with the modified script.

I may remove the theme specification from the preview script.
In that case, you can use any theme by setting the BAT_THEME environment variable.
`let $BAT_THEME = 'GitHub'`

**Comment by NicolaiRuckel** [comment]
That is actually a very good suggestion. I’ll do that. Thank you very much. :)
