### ISSUE TITLE
No option to list symbols

### ISSUE THREAD

**Issue by eulertour** [yuki-yano/fzf-preview.vim#247]
## Problems summary
There is no command that imitates `:CocList symbols`, e.g. `:CocCommand fzf-preview.CocSymbols`. Is this possible with the code currently?

**Comment by antoinemadec** [comment]
@eulertour , you can try this: https://github.com/antoinemadec/coc-fzf

@yuki-yano , if you want to add it to your plugin, you can take a look at how I implemented it:

1. https://github.com/antoinemadec/coc-fzf/blob/master/script/get_workspace_symbols.py
2. https://github.com/antoinemadec/coc-fzf/blob/master/autoload/coc_fzf/symbols.vim#L58

I hope this helps :smiley: ,
Antoine

**Comment by yuki-yano** [comment]
We need to pass an argument to symbols, but due to the way fzf-preview works, we cannot receive the result for dynamic queries.

As @antoinemadec said, you may want to use coc-fzf.
