### ISSUE TITLE
How to open directory files when not in git repo

### ISSUE THREAD

**Issue by kuntau** [yuki-yano/fzf-preview.vim#248]
Hi,

First of all, thank you for this extension, it has come a long way since I first saw it on Reddit.

This is not a problem, I'm just wondering if it's possible to dynamically open `FzfPreviewDirectoryFiles` or ` FzfPreviewGitFiles` based on whether I'm in a git repo or not?

Thank you

**Comment by yuki-yano** [comment]
Sorry for the late reply.

I think it is possible to implement a function in the Vim script that switches the command to be executed based on whether the current directory is a git repository or not.

**Comment by kuntau** [comment]
Any idea how?
