### ISSUE TITLE
VistaCtags show too much

### ISSUE THREAD

**Issue by d-miketa** [yuki-yano/fzf-preview.vim#251]
Hi, I'm trying to use VistaCtags with coc-pyright to generate a list of searchable symbols, populated both by libraries and files in the current working directory. Simply firing `:CocCommand fzf-preview.VistaCtags` shows everything I need, but also way more, e.g. entries in `node_modules` and Python libraries I won't be using. It also generates a corresponding ~200MB `tags` file in my `/tmp` folder. I'd ideally combine a (much much smaller) pre-made tag file plus symbols generated from the current working directory by coc. I can't figure out from the documentation if that's even possible. For what it's worth `:tag [library_class]` works and Vista shows current workspace symbols (using coc) perfectly well.

Otherwise I'm really enjoying the fzf workflow so far! Thank you for all the work and sharing it with us.

EDIT: I noticed that `CocCommand fzf-preview.Ctags` doesn't show anything, although `:tag [class]` works as expected. Maybe `fzf-preview` just can't see my `tags` file?

**Comment by yuki-yano** [comment]
Sorry for the late reply.

VistaCtags is dependent on vista's behavior, so you may have to deal with it there or implement a new resource in fzf-preview.

As for Ctags, it is possible that it is not working and I will investigate.

**Comment by d-miketa** [comment]
Thanks for the reply! Looking through the source codes again I noticed [your implementation](https://github.com/yuki-yano/fzf-preview.vim/blob/13c00e7dc3d7b68219e6cf5c8d3c5febb1fa7f4b/autoload/fzf_preview/remote/resource/vista.vim) calls `vista#executive#ctags#ProjectRun()` ([Vista's git](https://github.com/liuchengxu/vista.vim/blob/76f4039cafb3fe0d080fefbb3dd4b321257a80cb/autoload/vista/executive/ctags.vim#L402)), which generates ctags even if they already exist; leaving it here mostly in case anyone has a similar question. I decided to drop Vista but keep your plug-in and Gutentags for automatic tag generation. Everything works great as far as I can tell! Thank you for your work. :)
