### ISSUE TITLE
Document opening multiple files with TAB in preview window

### ISSUE THREAD

**Issue by demizer** [yuki-yano/fzf-preview.vim#256]
Hi! Thank you for making this excellent plugin.

I was struggling with opening multiple files after I forgot how to do it (press "TAB"), I only found it after watching the gif on the readme page.

Please add this to the help documentation.

Thanks again!

**Comment by yuki-yano** [comment]
This is not a feature of fzf-preview.vim, but of fzf itself, so I don't think it is necessary to write it in the fzf-preview documentation.
