### ISSUE TITLE
[Feature Request] Open all files in fzf-preview

### ISSUE THREAD

**Issue by charlesnicholson** [yuki-yano/fzf-preview.vim#257]
Thanks for writing fzf-preview, I use it every day and think it's great :)

Sorry if I missed this in the documentation, but I sometimes want to do an fzf-preview search (git or ripgrep), then inside the fzf-preview view, filter more by typing. Then I end up with a small number of files; I can select one and hit enter to open it.

Is there a way to open _all_ of the files that are not yet filtered away, instead of just _one_?

**Comment by yuki-yano** [comment]
In the default configuration of fzf-preview, you can select multiple files by pressing Tab.
Select multiple files and use split, vsplit, tabedit, etc. to open the selected ones.

**Comment by charlesnicholson** [comment]
I had no idea fzf / fzf-preview could do that! Thanks and sorry to bother you.
