### ISSUE TITLE
FZF search history feature request

### ISSUE THREAD

**Issue by onionka** [yuki-yano/fzf-preview.vim#261]
Hello! Thanks for this great plugin 👍 

I am trying to figure out for some time now, how to use FZF history. When I just simply set the `--history ~/.fzf.history` flag for FZF, the FZFPreview window won't open.

Wouldn't it be possible to add it as a new feature please? I would be super useful.

Thank you

**Comment by yuki-yano** [comment]
https://github.com/yuki-yano/fzf-preview.vim/pull/267
Here is an experimental implementation.
Now I need to write the doc.
Can you set up a `g:fzf_preview_history_dir` with this branch and try it out?

**Comment by yuki-yano** [comment]
I've decided to release it after all.
Please read the doc and try the settings.

**Comment by onionka** [comment]
It works very well 👍 
Thank you!
