### ISSUE TITLE
[Question] $FZF_PREVIEW_PREVIEW_BAT_THEME has no effect?

### ISSUE THREAD

**Issue by gniw** [yuki-yano/fzf-preview.vim#262]
## Problems summary
I want to change preview window, and file list color theme.
I read document, then set `$FZF_PREVIEW_PREVIEW_BAT_THEME`,
but It seems to have no effect...
Could you tell me what is the correct way to change bat theme?

### Expected

change theme

### Environment Information

- fzf-preview version (package.json): 2.0.15

- OS: Mac 10.15.7

- Vim/Neovim version: NVIM v0.4.4

### Provide a minimal init.vim

```vim
set nocompatible
set runtimepath^=~/.local/share/dein/repos/github.com/neoclide/coc.nvim
set runtimepath^=~/.local/share/dein/repos/github.com/junegunn/fzf
set runtimepath^=~/.local/share/dein/repos/github.com/ryanoasis/vim-devicons
syntax on
filetype plugin indent on

let g:coc_global_extensions = ['coc-fzf-preview']

let g:fzf_preview_use_dev_icons = 1
let g:fzf_preview_git_files_command   = 'git ls-files -co --exclude-standard'
let g:fzf_preview_grep_cmd            = 'rg --ignore-case --color=never --line-number --no-heading --sort=path'

let $FZF_PREVIEW_PREVIEW_BAT_THEME = 'gruvbox'
" let $FZF_PREVIEW_PREVIEW_BAT_THEME = 'ansi-dark'

nnoremap ; :
nnoremap : ;

```

### Screenshot

`let $FZF_PREVIEW_PREVIEW_BAT_THEME = 'gruvbox`

<img width="841" alt="2021-04-16 15 58 47" src="https://user-images.githubusercontent.com/6947659/114985542-e442cf00-9ecd-11eb-8fab-3cbfe7a44d01.png">

`let $FZF_PREVIEW_PREVIEW_BAT_THEME = 'ansi-dark`
<img width="841" alt="2021-04-16 15 58 50" src="https://user-images.githubusercontent.com/6947659/114985531-e016b180-9ecd-11eb-9a2c-eaf9509848f6.png">

### Dockerfile that reproduces the problem (if possible)

Sorry, I don't have it 😖

**Comment by jowi-papa** [comment]
+1 having the same issue

**Comment by yuki-yano** [comment]
I apologize for the lack of clarity.
The $FZF_PREVIEW_PREVIEW_BAT_THEME was the color schema applied to the preview of grep view.
To change the theme for other than grep view, try setting $BAT_THEME.

```
let $BAT_THEME = 'gruvbox-dark'
let $FZF_PREVIEW_PREVIEW_BAT_THEME = 'gruvbox-dark'
```

**Comment by gniw** [comment]
> The $FZF_PREVIEW_PREVIEW_BAT_THEME was the color schema applied to the preview of grep view.
To change the theme for other than grep view, try setting $BAT_THEME.

oh, I see.
I understand the difference between `$FZF_PREVIEW_PREVIEW_BAT_THEME` and `$BAT_THEME`.
thank you! :)

**Comment by yuki-yano** [comment]
The current specification is confusing and I may modify it in the future.

**Comment by yuki-yano** [comment]
Fixed so that $FZF_PREVIEW_PREVIEW_BAT_THEME is reflected in both.
This will be applied in the next release.

https://github.com/yuki-yano/fzf-preview.vim/commit/6ca32fec5f2a06e5d0c6ab8ca9bb613530f80639

**Comment by gniw** [comment]
Wow! Thank you so much!
