### ISSUE TITLE
Live grep

### ISSUE THREAD

**Issue by ayoisaiah** [yuki-yano/fzf-preview.vim#269]
Could you please add a live grep option like fzf.vim's `:Rg` command?

![image](https://user-images.githubusercontent.com/13372163/119043958-849a8080-b9b1-11eb-91d1-b03343614fbf.png)

**Comment by yuki-yano** [comment]
Please try `:CocCommand fzf-preview.ProjectGrep .`

**Comment by ayoisaiah** [comment]
Thanks!

**Comment by martasd** [comment]
Hi @yuki-yano. When I execute the command `:FzfPreviewProjectGrepRpc .` in vim, I get the live grep window equivalent to the screen above. When I hit `Esc` and execute the same command again, nothing happens. Any idea why this could be happening? I don't have this issue with any other command.
