### ISSUE TITLE
Migrate preview script from ruby to python

### ISSUE THREAD

**Issue by yuki-yano** [yuki-yano/fzf-preview.vim#27]

**Comment by tssm** [comment]
Do you plan to support Vim? If that's not the case, can I suggest Lua. If you like agree I can help with that

**Comment by yuki-yano** [comment]
The preview script is executed from fzf, so it must be an executable command independent of vim.

For this reason, I currently have Ruby scripts under the bin directory.
I plan to choose Python as an environment independent preview script.

**Comment by yuki-yano** [comment]
#39

**Comment by tssm** [comment]
Ah, got it. Thanks for the answer
