### ISSUE TITLE
Preview's highligt-line may not work in Vim

### ISSUE THREAD

**Issue by yuki-yano** [yuki-yano/fzf-preview.vim#285]
## Problems summary

(It's working well in my environment.)

The highlight-line returned from bat is not applied when previewing grep and help in Vim.
The --highlight-line option is passed in the preview script.
When I run fzf's --preview from Vim terminal, it is displayed correctly.

### Expected

Highlight-line is applied properly in all environments.

### Environment Information

- fzf-preview version (package.json):v2.7.2

- OS:macOS 10.15.7

- Vim/Neovim version: Vim 8.2.3403

**Comment by biosugar0** [comment]
Maybe, The theme of bat command causes this problem.
<img width="902" alt="スクリーンショット 2021-09-16 22 50 07" src="https://user-images.githubusercontent.com/18737819/133625173-0421dc47-5951-4f3d-aef6-ad1e1a6bc535.png">

**Comment by biosugar0** [comment]
ansi theme have not `lineHighlight`.
https://github.com/sharkdp/bat/issues/1730

**Comment by ceuk** [comment]
It's worth noting that if you set `$FZF_PREVIEW_PREVIEW_BAT_THEME` to an invalid theme name (case sensitive) it will fall back to ansi (which won't work)

**Comment by yuki-yano** [comment]
Fixed: https://github.com/yuki-yano/fzf-preview.vim/commit/674db2a001ec24a8675cf7146c8b50758c85bbe1
