### ISSUE TITLE
Breaks FZF's commands `Ctrl-T`, `Ctrl-X`, for opening files in search

### ISSUE THREAD

**Issue by jjant** [yuki-yano/fzf-preview.vim#3]
When using FZF preview, using pressing `Ctrl-T` doesn't open the file in a new tab like bare FZF does (it doesn't do anything with FZF preview).

**Comment by yuki-yano** [comment]
It worked normally in the environment of myself and acquaintance.
Please write about the version and mapping of vim you are using
