### ISSUE TITLE
[Feature request] Tags

### ISSUE THREAD

**Issue by kristijanhusak** [yuki-yano/fzf-preview.vim#44]
Only thing I'm missing to completely switch from fzf-vim to this is `:BTags`, which i use to jump to method or anything in a file. Any chance that can be added ?

**Comment by yuki-yano** [comment]
I want to support ctags.
Do you need BTags instead of just Tags?

**Comment by kristijanhusak** [comment]
I use BTags mostly, but i think that both can be easily supported at once.

**Comment by yuki-yano** [comment]
An experimental BufferTags command has been added. #45
The format, open function and preview script will be prepared.

BTags were easily obtained with the ctags command.
However, the Tags command is difficult because it needs to parse the tags file.

**Comment by yuki-yano** [comment]
Fix the above and added BufferTags at #45

**Comment by rlisowski** [comment]
@yuki-ycino I love it. Thank you for your hard work.

![BTags](https://user-images.githubusercontent.com/7737/74312900-e6ae1400-4d72-11ea-92ea-ff64f5e18e60.jpg)

**Comment by yuki-yano** [comment]
Pending https://github.com/yuki-ycino/fzf-preview.vim/tree/feature/ctags
