### ISSUE TITLE
[Feature request] Improved FzfPreviewOldFiles

### ISSUE THREAD

**Issue by kristijanhusak** [yuki-yano/fzf-preview.vim#46]
Hi,

I completely switched from fzf.vim to this.
I found one small difference between old files here and in fzf.vim. In fzf.vim, beside `v:oldfiles`, buflisted buffers are also listed. This is neat because in reality, those buffers are really an old file that you visited. Vim doesn't update oldfiles with these, but this is a good workaround for it. Would you consider adding it? Thanks!

**Comment by yuki-yano** [comment]
In fzf-preview.vim, you can select multiple resources by using `FzfPreviewFromResources`.

Running `:FzfPreviewFromResources buffer old (or project_old?)` will solve the problem.
I think it would be easier to process only the `v:oldfiles` with the OldFiles command.

**Comment by kristijanhusak** [comment]
That works great, thanks!
