### ISSUE TITLE
[Feature Request] '--preview-window' Support

### ISSUE THREAD

**Issue by addisonbeck** [yuki-yano/fzf-preview.vim#47]
Apologies if this is already implemented, I couldn't track it down if it was.

FZF has an option '--preview-window' that lets users customize certain aspects of the preview displayed. This can be seen [here](https://github.com/junegunn/fzf/blob/master/man/man1/fzf.1#L366).

Could this be exposed as a variable in the plugin?

**Comment by yuki-yano** [comment]
Added `g:fzf_preview_fzf_preview_window_option` in #50.
Please check.

**Comment by addisonbeck** [comment]
Works perfect! Thank you!
