### ISSUE TITLE
RipGrep greps filename with pattern instead of only content

### ISSUE THREAD

**Issue by jemag** [yuki-yano/fzf-preview.vim#55]
It seems that :FzfPreviewProjectGrep also greps filenames, and not only the content of the files.

For example, let's say I create an empty repository and add 2 files.

test.html content:
``` html
layer
```

and layer.html content:
``` html
bullshit
\*
}
```

If I do the command manually in a terminal: 
``` bash
➜ rg --line-number --no-heading layer ./
./test.html:1:layer
```
only the "layer" contained in test.html is returned.

If I use, :FzfPreviewProjectGrep, here is the result:
![image](https://user-images.githubusercontent.com/7985687/74619566-fe372500-5103-11ea-8cbf-a64c6730f99b.png)

It basically greps the filename. So if some text that I need to find is also in a filename, it will be really hard to find that text in the project, since the results will be heavily polluted.

I think it would make sense if it behave normally, as the version entered in a terminal.

**Comment by yuki-yano** [comment]
The problem can be solved by passing the nth option to fzf.
I didn't pass it because it was useful to search by filename, but I'm going to change it to allow options.

**Comment by yuki-yano** [comment]
Added experimentally in #59.
Please give me feedback on my proposal.

**Comment by jemag** [comment]
@yuki-ycino  I am having a bit of a hard time making it work. 

When the fzf-preview.vim plugin is loaded, I am sourcing the following file:
```
let g:fzf_preview_grep_command_options = fzf_preview#command#get_common_command_options() | let g:fzf_preview_grep_command_options = g:fzf_preview_grep_command_options . ' --nth=3'
nnoremap <leader>g :<C-u>FzfPreviewProjectGrep -fzf-args=g:fzf_preview_grep_command_options<CR>
```
However, since the last update, I am getting the following error while opening any  file with vim : 
![image](https://user-images.githubusercontent.com/7985687/74750872-6e47c700-523a-11ea-8b8b-b2f75bbdef16.png)

I am on commit f30c73b

**Comment by yuki-yano** [comment]
This example had its own vimrc configuration.
Please read https://github.com/yuki-ycino/fzf-preview.vim/blob/master/doc/fzf_preview_vim.txt#L456

For now `fzf_preview#command#get_common_command_options()` only works after VimEnter.

```
autocmd VimEnter * let g:fzf_preview_grep_command_options = fzf_preview#command#get_common_command_options() | let g:fzf_preview_grep_command_options = g:fzf_preview_grep_command_options . ' --nth=3'
nnoremap <leader>g :<C-u>FzfPreviewProjectGrep -fzf-args=g:fzf_preview_grep_command_options<CR>
```

**Comment by yuki-yano** [comment]
Fixed example
https://github.com/yuki-ycino/fzf-preview.vim/commit/972a16018818c95f9b800077cef33c6ebe8a2d1e

**Comment by jemag** [comment]
> Fixed example
972a160

Oops, at first I copied the example and it wasn't working so I thought the problem was with VimEnter and removed it. 

Thanks it works now!

Shouldn't 
`nnoremap <Leader>g :<C-u>FzfPreviewProjectGrep -fzf-args=g:fzf_preview_grep_command_options<Space>`

Instead be 
`nnoremap <Leader>g :<C-u>FzfPreviewProjectGrep -fzf-args=g:fzf_preview_grep_command_options<CR>`

(CR instead of Space? Works with CR for me)

**Comment by yuki-yano** [comment]
In the case of Space, you can pass arguments to rg.
Often, the search criteria is passed to rg first, so it uses spaces.

Such a setting is also convenient in visual mode
`xnoremap <Leader>g "sy:FzfPreviewProjectGrep<Space>-F<Space>"<C-r>=substitute(substitute(@s, '\n', '', 'g'), '/', '\\/', 'g')<CR>"`

**Comment by yuki-yano** [comment]
Also, it is easy to use commands again with Space.

**Comment by abenz1267** [comment]
Hm, i also stumbed across this "problem".

Isn't there a way to pass flags etc. so that this plugin also respects them when opening the floating window? The current solution/proposal seems kinda inelegant.

**Comment by yuki-yano** [comment]
It is difficult to distinguish between options passed to rg and options passed to fzf.
It is also difficult to process arguments with Vimscript.
Do you have any good ideas?

**Comment by abenz1267** [comment]
Oh man... i wish i could help, but i've never once written a vim plugin and my vim script knowledge is close to zero :-/

Sorry

**Comment by yuki-yano** [comment]
The `-fzf-args` option has been changed to the `-eval-fzf-args` option, and the value can be passed directly with the `-fzf-arg` option.

Look at #67.
