### ISSUE TITLE
Lots of commands don't work if you are launching neovim with fish

### ISSUE THREAD

**Issue by LinasBeres** [yuki-yano/fzf-preview.vim#56]
E.g. this is incorrect syntax with fish
let preview = '[[ "$(file --mime {})" =~ binary ]] && ' . g:fzf_binary_preview_command . ' || ' . g:fzf_preview_command

**Comment by yuki-yano** [comment]
Similar to #19.
I plan to add a variable that can set that part.

**Comment by yuki-yano** [comment]
Added g: fzf_preview_if_binary_command in #58
I can't try because there is no fish environment, but try `'[["(file --mime {})" = ~ binary]]'`.

**Comment by eilvelia** [comment]
Fish equivalent would be `'string match -q -r "binary" (file --mime {})'` (though, better use something like `"string match -q -r 'binary$' (file --mime-encoding {})"`)

But probably `fzf-preview.vim` should execute `/bin/bash -c` with those bash commands.

**Comment by Pitasi** [comment]
I'm having issues too when using fish.
As Bannerets said, shouldn't the commands be run with "/bin/bash -c" if bash is required? 

Thanks.
