### ISSUE TITLE
connot excuse preview_fzf_grep in zsh

### ISSUE THREAD

**Issue by Blacksuan19** [yuki-yano/fzf-preview.vim#57]
when using either `FzfPreviewBufferTags` or `FzfPreviewProjectGrep` on the preview window I get an error saying `zsh:1: permission denied preview_fzf_grep`, the file is excusable with the right permissions

ignore the directory it is pointing to, my config is stowed from there

![2020-02-21_10-58_1](https://user-images.githubusercontent.com/10248473/74680106-a29b9300-51fa-11ea-8cdd-125a4ca15b49.png)

![2020-02-21_10-58](https://user-images.githubusercontent.com/10248473/74680112-a5968380-51fa-11ea-945c-756d14ec8db0.png)

great work BTW, this adds a lot of things to the initial implementation

**Comment by yuki-yano** [comment]
The preview script is in the directory where the plugin is installed.
Do you have permission to execute the script?

Also try copying https://github.com/yuki-ycino/fzf-preview.vim/blob/master/bin/preview_fzf_grep and setting it to `g:fzf_preview_grep_preview_cmd`.

**Comment by Blacksuan19** [comment]
turns out the issue is because my config is linked across different partitions, copying the whole folder to .config (rather than symlinking) fixes the issue

**Comment by yuki-yano** [comment]
Is it not enough to place the preview script in an executable location and set it to `g:fzf_preview_grep_preview_cmd`?
(For example `/usr/local/bin`)

**Comment by Blacksuan19** [comment]
yes that works as intended as well
