### ISSUE TITLE
syntax error on python3.5 (not on python3.6)

### ISSUE THREAD

**Issue by ywpkwon** [yuki-yano/fzf-preview.vim#71]
First of all, deeply thanks for this great plugin!

I have multiple machines: some of them are still Ubuntu 16.04 with Python 3.5 and the other are Ubuntu 18.04 with Python 3.6, by default. When I do `FzfPreviewLines`, I got
![image](https://user-images.githubusercontent.com/18429284/75017437-da484c00-5441-11ea-8e38-a7053c5e335b.png)

I realized that it may be because of the `f'string'`, which is only for Python 3.6+.
![image](https://user-images.githubusercontent.com/18429284/75017647-4cb92c00-5442-11ea-8e05-c1b38942043c.png)

Would you consider supporting this plugin compatible to Python 3.5?
Or would you recommend/advise users using python3.6+ for their neovim?

**Comment by yuki-yano** [comment]
I wrote in the documentation that I checked in 3.6.
https://github.com/yuki-ycino/fzf-preview.vim/blob/master/doc/fzf_preview_vim.txt#L34

I'll guide you to use Python 3.6 or later, as there may be other issues.
