### ISSUE TITLE
ProjectGrep problems with ":"

### ISSUE THREAD

**Issue by abenz1267** [yuki-yano/fzf-preview.vim#72]
Hi,

when trying to search for a string containing a `:`, you won't get the proper results. See screenshot (i removed the filenames...).

![Screenshot_20200221_141738](https://user-images.githubusercontent.com/7055955/75038111-f84f9400-54b5-11ea-8707-c5a51f3470b0.png)

When searching for `touch:select` there won't be any results.

Regards

**Comment by yuki-yano** [comment]
I'll check it.
Thanks.

**Comment by yuki-yano** [comment]
I tried it but couldn't reproduce the bug, could you please list the sample file and the commands you ran separately?
