### ISSUE TITLE
Fzf preview appearance

### ISSUE THREAD

**Issue by jemag** [yuki-yano/fzf-preview.vim#79]
Is there a way to remove the transparency from the fzf-preview window?

Also, I know I can modify "g:fzf_preview_fzf_color_option" to control the color of fzf background. However, is there any way to make the background default to using the terminal color? If I don't specify any color, it seems the preview window will default to black instead of the terminal color.

**Comment by bpinto** [comment]
```
" floating window winblend value
let g:fzf_preview_floating_window_winblend = 15
```

use this for transparency, values: [0-100]

**Comment by jemag** [comment]
Thanks a lot! I thought window_winblend was for something totally different.

**Comment by yuki-yano** [comment]
@bpinto Thanks!

Should you disable default?

**Comment by bpinto** [comment]
I guess it's not possible, but it would be nice to reuse the same colorscheme as vim.
