### ISSUE TITLE
ProjectGrep super slow with large codebases

### ISSUE THREAD

**Issue by abenz1267** [yuki-yano/fzf-preview.vim#80]
Hi,

using `:FzfPreviewProjectGrep` is super slow with larger codebases. It literally crashes at some point. Try it with a large codebase...kinda extreme example: https://github.com/torvalds/linux. But you get the point.

Using `:FzfPreviewProjectGrep <term>` works reasonably fast though, so i assume it's because of the fact it renders every file into the list, which IMO should be avoided anyways. Tbh that usage seems to be better in general... performance-wise.

I think when opening the floating window without a searching term, no sources should be listed and the prompt in the floating window would call the according command afterwards, that way you'd also do stuff like `-w <term>`.

What do you think? Does it make sense?

Regards

**Comment by yuki-yano** [comment]
It is difficult to generate resources to pass to fzf in stages.
To solve the crash problem, FzfPreviewProjectGrep changes the argument to mandatory

The same behavior as before can be realized with `FzfPreviewProjectGrep .`.
Thanks

**Comment by yuki-yano** [comment]
Fixed 8093128dce5a24eab6c221c1bcbfc3b8fa575e32
