### ISSUE TITLE
FzfPreviewProjectFiles and gxargs

### ISSUE THREAD

**Issue by djasnowski** [yuki-yano/fzf-preview.vim#81]
I did the above command on my nvim and I got `[bat error]: 'gxargs': No such file or directory (os error 2)`

Which is weird because: 
```
➜ which xargs
/usr/bin/xargs
```

Nvim debug

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local
```

I am MacOS Catalina (10.15.3) - MacBook Pro (Retina, 13-inch, Early 2015)

So in the postprocess command, I took out the g in `gxargs` and then I got:

```
➜ xargs -d "\n" ls —color
xargs: illegal option -- d
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
```

**Comment by yuki-yano** [comment]
Try installing gxargs.
`$ brew install findutils`

**Comment by djasnowski** [comment]
Thanks -- that fixed it @yuki-ycino

**Comment by djasnowski** [comment]
I'm still getting `[bat error]: 'd': "No such file or directory (os error 2)`

What I used: `" let g:fzf_preview_filelist_postprocess_command = 'xargs -d "\n" exa --color=always' " Use exa`

**Comment by djasnowski** [comment]
That is fine. I must have something else missing. I'll go ahead and close this. 

One last question... is there a way to get a project list of all of the git only files like ProjectPreviewFiles?

**Comment by yuki-yano** [comment]
Is it useless in FzfPreviewGitFiles?

**Comment by djasnowski** [comment]
@yuki-ycino It is. I did it on a new empty git project. I am a baboon. Carry on and great job.
