### ISSUE TITLE
How to pass path parameter to FzfPreviewDirectoryFiles ?

### ISSUE THREAD

**Issue by guillaumewuip** [yuki-yano/fzf-preview.vim#83]
I would like to `:FzfPreviewDirectoryFiles  expand('%:h')` but it looks like `FzfPreviewDirectoryFiles` doesn't accept a path parameter. Am I wrong ?

**Comment by yuki-yano** [comment]
The DirectoryFiles command was implemented quickly as there was a request to use it in a directory other than git.

I didn't think much because I didn't use it.
Thank you. I consider receiving parameters.

For now, try using it after cd.

**Comment by guillaumewuip** [comment]
Ok I understand :)

I'm willing to help with a PR if you would accept this kind of contribution.  I've read the code a bit. Do you think it would be enough to change `fzf_preview#resource#directory_files()` to accept a parameter ?

https://github.com/yuki-ycino/fzf-preview.vim/blob/55f1eaf06dc1667909dd1d5947369199a8df57f5/autoload/fzf_preview/resource.vim#L19-L22

**Comment by yuki-yano** [comment]
The FromResources command uses no arguments, so need to use variable arguments.

https://github.com/yuki-ycino/fzf-preview.vim/blob/master/autoload/fzf_preview/resource.vim#L193

**Comment by guillaumewuip** [comment]
Ok, thanks for the hint. I will try something !
