### ISSUE TITLE
<Tab> in the Preview Window

### ISSUE THREAD

**Issue by fsmiamoto** [yuki-yano/fzf-preview.vim#85]
I was wondering about the use of <Tab> key in the preview window, as shown in a GIF.
Correct me if I'm wrong but there doesn't seem to be any written reference of it's functionality, therefore I think we should probably add a description to the README.

Also, would it be possible to remap it just like the other functions (split, vsplit, etc)? 
If this is something that would need to be worked upon, I can definitely take a try!

**Comment by yuki-yano** [comment]
Multi Select (Tab) is a function of fzf, so please check the fzf documentation.
There are currently no plans to make Tabs modifiable.
