### ISSUE TITLE
Terminal closing message

### ISSUE THREAD

**Issue by ubmarco** [yuki-yano/fzf-preview.vim#86]
Hi, this is a follow-up bug report on the problem I reported in https://github.com/hardcoreplayers/ThinkVim/issues/93#issuecomment-593312974.
When I run `FzfPreviewDirectoryFiles` or other preview commands, I see the following message on `ESC` or `Enter`.
```
-- TERMINAL --
Close "term://.//7785:cat '/tmp/nvim0PUsUl/3'|'/home/marco/.cache/vim/dein/repos/github.com/junegunn/fzf/bin/fzf' --multi --reverse --ansi 
--bind=ctrl-d:preview-page-down,ctrl-u:preview-page-up,?:toggle-preview   --expect=ctrl-v,ctrl-x,ctrl-q,ctrl-t --prompt="DirectoryFiles> " 
--preview='[[ "$(file --mime {})" =~ binary ]] && echo "{} is a binary file" || head -100 {-1}'  --no-height > /tmp/nvim0PUsUl/2;#FZF"?    
[Y]es, (N)o, (C)ancel:
```
Here's a screencast:
![Peek 2020-03-02 10-39](https://user-images.githubusercontent.com/839934/75664198-5cbae200-5c72-11ea-891e-4c5471d15472.gif)
Might that be related to this plugin?

**Comment by duanmuq** [comment]
I have the same question. 
Now, I  remove the "set confirm" form the init.vim, it works.

But I still want to find way to get the "set confirm" back, it's useful for remender me to save buffer

**Comment by yuki-yano** [comment]
I cant reproduce.
Please write the version of neovim and fzf.

**Comment by yuki-yano** [comment]
A similar problem has also occurred in fzf.vim, so it may not be a problem with this plugin.
https://github.com/mhinz/neovim-remote/issues/47

**Comment by ubmarco** [comment]
Version:
```
$ fzf --version
0.17.4 (f0fe79d)

$ nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by ubmarco** [comment]
For me, commenting out `set confirm` from the thinkvim config also fixes the issue.

**Comment by yuki-yano** [comment]
0.17.4 was released in 2018. https://github.com/junegunn/fzf/releases/tag/0.17.4
Try the latest release.

**Comment by ubmarco** [comment]
I updated to 0.20.0, same issue.

**Comment by ubmarco** [comment]
I actually don't understand where this issue could come from. Is that related to `fzf`, `fzf.vim`, `fzf-preview.vim`, my `xfce4-terminal` or `neovim`? It looks like `fzf-preview.vim` calls `fzf` to get the file list and displays it. The call to `fzf` goes through a shell which is closed at the end for which `nvim` asks for confirmation.

**Comment by jemag** [comment]
This issue appeared for me when I updated my plugins (including fzf and fzf-preview). I did not update neovim however, so I am guessing that this behavior appeared from one of the updated plugins.

**Comment by glepnir** [comment]
>This issue appeared for me when I updated my plugins (including fzf and fzf-preview).  

yes .when update ,i aslo get this problem.

**Comment by yuki-yano** [comment]
Solved by changing the buffer's `bdelete` to `bdelete!`.
Please update plugin.

**Comment by ubmarco** [comment]
Thanks a lot, it works.
