### ISSUE TITLE
Restore :FzfPreviewProjectGrep functionality

### ISSUE THREAD

**Issue by lynndylanhurley** [yuki-yano/fzf-preview.vim#87]
It looks like [this commit](8093128dce5a24eab6c221c1bcbfc3b8fa575e32) changed the behavior of the `FzfPreviewProjectGrep` command to require an argument.

Before I was able to open the preview interface and immediately begin narrowing down the results by typing. Now I need to enter the search term into the status line first, and then once the preview window appears I need to re-enter the search term to begin refining the search.

Is there a way to restore the original behavior (i.e. the way it worked before 8093128dce5a24eab6c221c1bcbfc3b8fa575e32)?

**Comment by yuki-yano** [comment]
See #80 
You can use `FzfPreviewProjectGrep .`.

**Comment by lynndylanhurley** [comment]
Thanks @yuki-ycino !
