### ISSUE TITLE
Clear input with C-u

### ISSUE THREAD

**Issue by bpinto** [yuki-yano/fzf-preview.vim#88]
Sorry for raising an issue instead of working on a PR.

It would be nice to support control + u to clear the input now that there is `-resume` option.

**Comment by yuki-yano** [comment]
C-u assigns to preview page up by default.
I think C-w is enough in most cases.

**Comment by bpinto** [comment]
I didn't know about `C-w` I think it's not documented?

Is there a way to remap these commands? I'd prefer to use C-u since that's what I use on all terminal commands, etc.

P.S.: Vim also uses C-b and C-f for page up and down.

```
[Control][b] - Move back one full screen
[Control][f] - Move forward one full screen
[Control][d] - Move forward 1/2 screen
[Control][u] - Move back (up) 1/2 screen
```

**Comment by yuki-yano** [comment]
Use `g:fzf_preview_preview_key_bindings`
Default is `'ctrl-d:preview-page-down,ctrl-u:preview-page-up,?:toggle-preview'`

C-w is a general Emacs key binding, so I don't think it needs any documentation.

**Comment by bpinto** [comment]
Thanks 👍 

I've never used emacs, only vim. So when it comes to other keybindings I'm only used to [readline keybindings](https://readline.kablamo.org/emacs.html) which is used by many shells, and there C-x removes last word and C-u removes everything until the beginning of the line.

**Comment by bpinto** [comment]
Adding information for anyone else reading this issue.

---

By default fzf maps `ctrl-u` to clear text until the beginning of line, so to get this behaviour inside `fzf-preview.vim` window all one needs to do is to remove the overriding binding:

default: `let g:fzf_preview_preview_key_bindings = 'ctrl-d:preview-page-down,ctrl-u:preview-page-up,?:toggle-preview'`

final: `let g:fzf_preview_preview_key_bindings = 'ctrl-d:preview-page-down,?:toggle-preview'`

**Comment by phongvcao** [comment]
@bpinto @yuki-ycino the above trick didn't work for me for some reasons. Just removing `<C-u>` from `g:fzf_preview_preview_key_bindings` just doesn't work for me.

**Comment by yuki-yano** [comment]
A recent update should have made it work well.
Please update the plugin and give it a try.
#174

**Comment by phongvcao** [comment]
@yuki-ycino which recent update are you talking about? I tried updating the plugin using PlugUpdate! (vim-plug) but nothing was updated, and `<C-u>` to clear binding still doesn't work.

**Comment by yuki-yano** [comment]
It works fine when I try the minimum configuration in my environment.
I don't know much about vim-plug, but try a complete reinstallation of the plugin, etc.

If you are using coc extensions, you can use the coc command to update them.

```vim
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'yuki-ycino/fzf-preview.vim', { 'branch': 'release', 'do': ':UpdateRemotePlugins' }
call plug#end()

let g:fzf_preview_preview_key_bindings = 'ctrl-d:preview-page-down,?:toggle-preview'
```

![Kapture 2020-09-20 at 19 42 53 2020-09-20 19_46_25](https://user-images.githubusercontent.com/5423775/93709550-0e235580-fb7a-11ea-8408-bfd0b85d7bc7.gif)

**Comment by phongvcao** [comment]
Ok I see. I upgraded fzf-preview.vim and now everything works. Thanks @yuki-ycino
