### ISSUE TITLE
Is there 'finding lines in all buffers" in addition to `FzfPreviewLines`?

### ISSUE THREAD

**Issue by ywpkwon** [yuki-yano/fzf-preview.vim#89]
Hi, I'm really enjoying `fzf-preview`. Thanks for this valuable project!

`FzfPreviewLines` seems for finding lines in **current buffer**. Is there a similar command but for finding lines in **all loaded buffers**?

I found that, in `junegunn/fzf.vim`, there are
```
:Lines [QUERY] | Lines in loaded buffers
:BLines [QUERY] | Lines in the current buffer
```

**Comment by yuki-yano** [comment]
As I thought, implementation including preview may take a little time.
I will consider implementing it in the future.
Thanks.

**Comment by danielo515** [comment]
Here is another interessed one!

**Comment by sushovannits** [comment]
Same here

**Comment by yuki-yano** [comment]
Add `FzfPreviewBufferLines` command from #104
