### ISSUE TITLE
setting fzf_preview_filelist_postprocess_command causes plugin to perform much slower

### ISSUE THREAD

**Issue by RonanMacF** [yuki-yano/fzf-preview.vim#91]
Hi,

I have a codebase of about 230,000 files. With a setup including bat, ripgrep and no filelist_postprocess command it performs relatively good. Once I execute the `FzfPreviewDirectoryFiles` command from the root of my project the floating window appears in just under 2 seconds, not ideal but good enough.

I have since decided to add a bit of colour to the filelist by installing exa and changing the filelist_postprocess command to the one you provided. When I execute the same command it then takes ~10 seconds for it to appear, thinking that maybe it is just due to exa being slower to ls I tried using dircolors but that also had a delay of 5 seconds.

Is there any way to speed this up?

**Comment by yuki-yano** [comment]
I think it is difficult to solve the slow execution of the command.
You may need to find a command to do the colorize faster.
