### ISSUE TITLE
Issue With Default Shell Programing

### ISSUE THREAD

**Issue by louishuyng** [yuki-yano/fzf-preview.vim#96]
- I have some issues when using fish shell programing. How can i config the default shell programing like as bash or zsh when using preview
- Here is my screenshot when using FzfPreviewGitStatus Command in Neovim:
<img width="454" alt="Screen Shot 2020-03-12 at 3 39 58 PM" src="https://user-images.githubusercontent.com/40130936/76503081-bba10800-6477-11ea-9331-15b04db29e78.png">

**Comment by zoomido** [comment]
I'm also using fish and I've fixed it by setting this in my init.vim:
`let g:fzf_preview_if_binary_command = "test (file -b --mime-encoding {}) = 'binary'" `

It will use the builtin `test` and then use `file` to get the mime-encoding (-b is to only output the mime-encoding and skip the filename) and compare this to `binary`

**Comment by louishuyng** [comment]
Many thanks bro you save my life <3

**Comment by yuki-yano** [comment]
Sorry for the late reply.

@zoomido Thanks.

**Comment by toyboot4e** [comment]
It doesn't work with `FzfPreviewProjectFiles`, where `&&` is used after the test.

Instead, I start Vim with `env SHELL=/bin/bash` (via an alias). It's not perfect, but it works anyway.

Edit: finally this is the solution for me:
```vim
if executable('fish')
    " use fish for embedded terminals
    set shell=fish
    " use bash for else
    let $SHELL = 'bash'
endif
```

**Comment by cjbarroso** [comment]
Thank you, it worked perfectly on my init.vim
