### ISSUE TITLE
Tweak :FzfPreviewBuffers to display buffers in MRU order

### ISSUE THREAD

**Issue by zoomido** [yuki-yano/fzf-preview.vim#97]
Found an old issue where this is referenced: https://github.com/yuki-ycino/fzf-preview.vim/issues/60#issuecomment-599710639
Still would like it to be fixed though since it's implemented in fzf.vim.

**Comment by lynndylanhurley** [comment]
@zoomido I would also like to do this. did you find a way?

**Comment by yuki-yano** [comment]
Buffer sorting is implemented by using MRU.
This is an experimental feature and may have bugs.
#119

**Comment by lynndylanhurley** [comment]
#119 completely solves my problem. Thanks @yuki-ycino!!
