### ISSUE TITLE
FzfPreviewGitStatus custom preview 

### ISSUE THREAD

**Issue by jlesquembre** [yuki-yano/fzf-preview.vim#99]
First, thanks for writing fzf-preview, I discovered it recently and is a great plugin, I'm replacing all my custom fzf config with it.

I have a feature request, to me, it would make sense to be able to customize the preview for files in the git status. While for the normal file preview I want to use `bat`, for `git diff` I'd like to use [delta](https://github.com/dandavison/delta)
Maybe we can have a new variable called `g:fzf_gitdiff_preview_command`?

**Comment by yuki-yano** [comment]
Add `g:fzf_preview_git_status_preview_command` from #100

**Comment by jlesquembre** [comment]
Thanks!
